In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
url_file=f"result/lsr_std_math.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','rf','time_rf','fop','time_fop']
table['time_total'] = table['time_rf']+table['time_fop']

table_math = table
table_math

       instance       rf  time_rf      fop  time_fop  time_total
0      52_1.txt   8915.4     0.49   8751.6      0.73        1.22
1      52_2.txt   8908.0     0.49   8852.8      0.94        1.43
2      52_3.txt   8648.6     0.46   8631.4      0.56        1.02
3      52_4.txt   9227.0     0.51   9076.6      0.96        1.47
4      52_5.txt   9758.5     0.57   9758.5      0.88        1.45
..          ...      ...      ...      ...       ...         ...
103  52_104.txt  39973.5     0.20  38400.0      0.20        0.40
104  52_105.txt  40533.0     0.19  39099.8      0.20        0.39
105  52_106.txt  45220.6     0.22  41933.6      0.21        0.43
106  52_107.txt  39315.8     0.19  38988.2      0.19        0.38
107  52_108.txt  43407.2     0.22  40813.2      0.20        0.42

[108 rows x 6 columns]

In [5]:
latex_table_math = table_math.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Solução viável encontrada pela matheuristica RF+FOP",  # The caption to appear above the table in the LaTeX document
    label="tab:sol_viavel_rf_fop",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_math)

\begin{table}[htbp]
\caption{Solução viável encontrada pela matheuristica RF+FOP}
\label{tab:sol_viavel_rf_fop}
\begin{tabular}{lrrrrr}
\toprule
instance & rf & time_rf & fop & time_fop & time_total \\
\midrule
52_1.txt & 8915.40 & 0.49 & 8751.60 & 0.73 & 1.22 \\
52_2.txt & 8908.00 & 0.49 & 8852.80 & 0.94 & 1.43 \\
52_3.txt & 8648.60 & 0.46 & 8631.40 & 0.56 & 1.02 \\
52_4.txt & 9227.00 & 0.51 & 9076.60 & 0.96 & 1.47 \\
52_5.txt & 9758.50 & 0.57 & 9758.50 & 0.88 & 1.45 \\
52_6.txt & 10308.00 & 0.56 & 10101.50 & 1.12 & 1.68 \\
52_7.txt & 9695.50 & 0.50 & 9662.50 & 0.86 & 1.36 \\
52_8.txt & 10096.50 & 0.55 & 10080.00 & 0.97 & 1.52 \\
52_9.txt & 10312.00 & 0.53 & 10306.40 & 0.84 & 1.37 \\
52_10.txt & 11198.60 & 0.54 & 10952.00 & 0.88 & 1.42 \\
52_11.txt & 10422.60 & 0.59 & 10422.60 & 0.94 & 1.53 \\
52_12.txt & 10793.00 & 0.55 & 10773.60 & 0.98 & 1.53 \\
52_13.txt & 13664.60 & 0.30 & 13369.00 & 0.33 & 0.63 \\
52_14.txt & 12686.20 & 0.35 & 12309.80 & 0.49 & 0.84 \\
52_15.txt & 13529.40 & 0.32 & 13328.20 & 0.37 & 0.69 \\
52_16.txt & 12346.40 & 0.32 & 11909.40 & 0.41 & 0.73 \\
52_17.txt & 14618.00 & 0.30 & 14497.50 & 0.36 & 0.66 \\
52_18.txt & 13704.00 & 0.35 & 13334.50 & 0.44 & 0.79 \\
52_19.txt & 14267.00 & 0.29 & 14004.50 & 0.38 & 0.67 \\
52_20.txt & 13944.50 & 0.35 & 13523.50 & 0.45 & 0.80 \\
52_21.txt & 15290.40 & 0.31 & 14946.60 & 0.46 & 0.77 \\
52_22.txt & 14144.00 & 0.32 & 14122.20 & 0.39 & 0.71 \\
52_23.txt & 14797.60 & 0.30 & 14577.60 & 0.35 & 0.65 \\
52_24.txt & 14764.40 & 0.35 & 14130.60 & 0.51 & 0.86 \\
52_25.txt & 26687.00 & 0.19 & 25992.00 & 0.16 & 0.35 \\
52_26.txt & 23173.60 & 0.22 & 21884.40 & 0.17 & 0.39 \\
52_27.txt & 26201.60 & 0.20 & 25126.40 & 0.15 & 0.35 \\
52_28.txt & 23653.20 & 0.23 & 21494.80 & 0.18 & 0.41 \\
52_29.txt & 27645.00 & 0.20 & 27176.00 & 0.17 & 0.37 \\
52_30.txt & 24699.50 & 0.22 & 22796.00 & 0.17 & 0.39 \\
52_31.txt & 27397.00 & 0.19 & 26808.50 & 0.14 & 0.33 \\
52_32.txt & 24998.00 & 0.22 & 23935.00 & 0.17 & 0.39 \\
52_33.txt & 28619.00 & 0.19 & 28268.20 & 0.15 & 0.34 \\
52_34.txt & 27631.60 & 0.21 & 24975.40 & 0.17 & 0.38 \\
52_35.txt & 27938.80 & 0.20 & 27190.00 & 0.15 & 0.35 \\
52_36.txt & 26390.20 & 0.22 & 24450.00 & 0.15 & 0.37 \\
52_37.txt & 10884.20 & 0.37 & 10768.20 & 0.48 & 0.85 \\
52_38.txt & 12350.00 & 0.35 & 12235.60 & 0.48 & 0.83 \\
52_39.txt & 10979.60 & 0.39 & 10881.20 & 0.52 & 0.91 \\
52_40.txt & 12186.60 & 0.32 & 12102.80 & 0.46 & 0.78 \\
52_41.txt & 12435.50 & 0.37 & 12304.00 & 0.52 & 0.89 \\
52_42.txt & 14181.50 & 0.33 & 14137.50 & 0.46 & 0.79 \\
52_43.txt & 12528.50 & 0.40 & 12469.50 & 0.54 & 0.94 \\
52_44.txt & 13924.00 & 0.30 & 13738.00 & 0.38 & 0.68 \\
52_45.txt & 13537.60 & 0.42 & 13447.00 & 0.57 & 0.99 \\
52_46.txt & 15375.20 & 0.36 & 15064.80 & 0.41 & 0.77 \\
52_47.txt & 13809.60 & 0.38 & 13668.00 & 0.52 & 0.90 \\
52_48.txt & 15344.80 & 0.37 & 15293.40 & 0.52 & 0.89 \\
52_49.txt & 15974.80 & 0.29 & 15850.40 & 0.50 & 0.79 \\
52_50.txt & 16120.20 & 0.28 & 15890.40 & 0.54 & 0.82 \\
52_51.txt & 15530.40 & 0.30 & 15454.20 & 0.36 & 0.66 \\
52_52.txt & 15516.00 & 0.29 & 15369.60 & 0.52 & 0.81 \\
52_53.txt & 17283.00 & 0.34 & 16874.50 & 0.56 & 0.90 \\
52_54.txt & 17767.50 & 0.32 & 17533.00 & 0.65 & 0.97 \\
52_55.txt & 17102.50 & 0.32 & 16715.50 & 0.49 & 0.81 \\
52_56.txt & 17823.00 & 0.37 & 17403.50 & 0.45 & 0.82 \\
52_57.txt & 18424.60 & 0.38 & 18272.20 & 0.61 & 0.99 \\
52_58.txt & 19012.80 & 0.45 & 18968.80 & 0.38 & 0.83 \\
52_59.txt & 18489.60 & 0.37 & 18014.00 & 0.55 & 0.92 \\
52_60.txt & 19355.20 & 0.37 & 18863.80 & 0.56 & 0.93 \\
52_61.txt & 29112.20 & 0.20 & 28101.40 & 0.17 & 0.37 \\
52_62.txt & 26779.20 & 0.23 & 25566.60 & 0.20 & 0.43 \\
52_63.txt & 27845.00 & 0.20 & 27136.20 & 0.16 & 0.36 \\
52_64.txt & 27125.80 & 0.23 & 25208.20 & 0.22 & 0.45 \\
52_65.txt & 30254.50 & 0.21 & 29365.00 & 0.17 & 0.38 \\
52_66.txt & 29410.00 & 0.24 & 27482.50 & 0.18 & 0.42 \\
52_67.txt & 30051.00 & 0.21 & 29141.00 & 0.15 & 0.36 \\
52_68.txt & 29535.00 & 0.23 & 27699.50 & 0.16 & 0.39 \\
52_69.txt & 32008.60 & 0.20 & 30521.20 & 0.17 & 0.37 \\
52_70.txt & 30756.60 & 0.22 & 29317.80 & 0.17 & 0.39 \\
52_71.txt & 31841.60 & 0.21 & 31307.40 & 0.18 & 0.39 \\
52_72.txt & 31858.80 & 0.21 & 29460.60 & 0.17 & 0.38 \\
52_73.txt & 14545.40 & 0.21 & 14468.40 & 0.17 & 0.38 \\
52_74.txt & 18567.80 & 0.20 & 18478.80 & 0.20 & 0.40 \\
52_75.txt & 15328.20 & 0.21 & 15275.20 & 0.19 & 0.40 \\
52_76.txt & 18768.80 & 0.19 & 18305.20 & 0.20 & 0.39 \\
52_77.txt & 18996.50 & 0.22 & 18875.50 & 0.25 & 0.47 \\
52_78.txt & 24316.00 & 0.21 & 23224.00 & 0.20 & 0.41 \\
52_79.txt & 19147.50 & 0.22 & 18882.50 & 0.22 & 0.44 \\
52_80.txt & 24567.50 & 0.20 & 23583.50 & 0.19 & 0.39 \\
52_81.txt & 21249.20 & 0.22 & 21206.00 & 0.24 & 0.46 \\
52_82.txt & 27857.60 & 0.22 & 26995.80 & 0.24 & 0.46 \\
52_83.txt & 21855.80 & 0.23 & 21716.00 & 0.23 & 0.46 \\
52_84.txt & 26856.40 & 0.21 & 26661.20 & 0.20 & 0.41 \\
52_85.txt & 20345.00 & 0.18 & 19876.60 & 0.23 & 0.41 \\
52_86.txt & 23358.40 & 0.19 & 23171.40 & 0.21 & 0.40 \\
52_87.txt & 20394.60 & 0.19 & 19992.40 & 0.23 & 0.42 \\
52_88.txt & 23284.20 & 0.19 & 23027.20 & 0.20 & 0.39 \\
52_89.txt & 23522.00 & 0.21 & 23446.00 & 0.25 & 0.46 \\
52_90.txt & 28874.00 & 0.21 & 27459.50 & 0.25 & 0.46 \\
52_91.txt & 23603.00 & 0.21 & 23571.00 & 0.28 & 0.49 \\
52_92.txt & 27693.50 & 0.21 & 27183.50 & 0.23 & 0.44 \\
52_93.txt & 26523.60 & 0.22 & 26492.80 & 0.28 & 0.50 \\
52_94.txt & 31453.40 & 0.23 & 30791.80 & 0.25 & 0.48 \\
52_95.txt & 27119.40 & 0.23 & 26917.80 & 0.29 & 0.52 \\
52_96.txt & 30740.60 & 0.23 & 30164.00 & 0.26 & 0.49 \\
52_97.txt & 35483.00 & 0.17 & 34075.80 & 0.15 & 0.32 \\
52_98.txt & 35118.60 & 0.17 & 34567.40 & 0.18 & 0.35 \\
52_99.txt & 35423.00 & 0.17 & 34697.20 & 0.17 & 0.34 \\
52_100.txt & 35220.00 & 0.18 & 34286.00 & 0.16 & 0.34 \\
52_101.txt & 38820.00 & 0.19 & 36941.00 & 0.18 & 0.37 \\
52_102.txt & 43061.00 & 0.21 & 38429.50 & 0.16 & 0.37 \\
52_103.txt & 38115.50 & 0.19 & 37336.00 & 0.19 & 0.38 \\
52_104.txt & 39973.50 & 0.20 & 38400.00 & 0.20 & 0.40 \\
52_105.txt & 40533.00 & 0.19 & 39099.80 & 0.20 & 0.39 \\
52_106.txt & 45220.60 & 0.22 & 41933.60 & 0.21 & 0.43 \\
52_107.txt & 39315.80 & 0.19 & 38988.20 & 0.19 & 0.38 \\
52_108.txt & 43407.20 & 0.22 & 40813.20 & 0.20 & 0.42 \\
\bottomrule
\end{tabular}
\end{table}

In [6]:
print(table_math['time_total'].max())
print(table_math['time_total'].mean())

1.6800000000000002
0.6518518518518519

In [7]:
url_file=f"result/lsr_std_mip_feasible_first.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval0','bound0','gap0','time0','nodes0','opt0']

table_first_feasible = table
table_first_feasible = table_first_feasible[['instance','objval0','time0']]
table_first_feasible

       instance   objval0  time0
0      52_1.txt   12770.8    0.0
1      52_2.txt   12827.8    0.0
2      52_3.txt   13398.0    0.0
3      52_4.txt   13413.4    0.0
4      52_5.txt   13936.5    0.0
..          ...       ...    ...
103  52_104.txt  119959.5    0.0
104  52_105.txt  129011.2    0.0
105  52_106.txt  118980.0    0.0
106  52_107.txt  128970.4    0.0
107  52_108.txt  119152.0    0.0

[108 rows x 3 columns]

In [8]:
latex_table = table_first_feasible.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Primeira solução viável encontrada pelo solver",  # The caption to appear above the table in the LaTeX document
    label="tab:primeiro_sol_viavel",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table)

\begin{table}[htbp]
\caption{Primeira solução viável encontrada pelo solver}
\label{tab:primeiro_sol_viavel}
\begin{tabular}{lrr}
\toprule
instance & objval0 & time0 \\
\midrule
52_1.txt & 12770.80 & 0.00 \\
52_2.txt & 12827.80 & 0.00 \\
52_3.txt & 13398.00 & 0.00 \\
52_4.txt & 13413.40 & 0.00 \\
52_5.txt & 13936.50 & 0.00 \\
52_6.txt & 15513.00 & 0.00 \\
52_7.txt & 14379.50 & 0.00 \\
52_8.txt & 15175.50 & 0.00 \\
52_9.txt & 15432.80 & 0.00 \\
52_10.txt & 17183.20 & 0.00 \\
52_11.txt & 16616.00 & 0.00 \\
52_12.txt & 16412.80 & 0.00 \\
52_13.txt & 27121.00 & 0.00 \\
52_14.txt & 22392.60 & 0.00 \\
52_15.txt & 26814.80 & 0.00 \\
52_16.txt & 22833.20 & 0.00 \\
52_17.txt & 27831.50 & 0.00 \\
52_18.txt & 23954.50 & 0.00 \\
52_19.txt & 28477.00 & 0.00 \\
52_20.txt & 24170.00 & 0.00 \\
52_21.txt & 29276.00 & 0.00 \\
52_22.txt & 24865.60 & 0.00 \\
52_23.txt & 29559.40 & 0.00 \\
52_24.txt & 27899.20 & 0.00 \\
52_25.txt & 90899.80 & 0.00 \\
52_26.txt & 70697.00 & 0.00 \\
52_27.txt & 87234.60 & 0.00 \\
52_28.txt & 69035.20 & 0.00 \\
52_29.txt & 91919.50 & 0.00 \\
52_30.txt & 71556.00 & 0.00 \\
52_31.txt & 91817.00 & 0.00 \\
52_32.txt & 71046.00 & 0.00 \\
52_33.txt & 95331.20 & 0.00 \\
52_34.txt & 70328.00 & 0.00 \\
52_35.txt & 92964.00 & 0.00 \\
52_36.txt & 72782.40 & 0.00 \\
52_37.txt & 20698.80 & 0.00 \\
52_38.txt & 20420.60 & 0.00 \\
52_39.txt & 20990.60 & 0.00 \\
52_40.txt & 20945.60 & 0.00 \\
52_41.txt & 21114.00 & 0.00 \\
52_42.txt & 24287.50 & 0.00 \\
52_43.txt & 20458.50 & 0.00 \\
52_44.txt & 22439.00 & 0.00 \\
52_45.txt & 21563.20 & 0.00 \\
52_46.txt & 25384.80 & 0.00 \\
52_47.txt & 23000.00 & 0.00 \\
52_48.txt & 24886.40 & 0.00 \\
52_49.txt & 32185.20 & 0.00 \\
52_50.txt & 29632.40 & 0.00 \\
52_51.txt & 32342.40 & 0.00 \\
52_52.txt & 30255.20 & 0.00 \\
52_53.txt & 33452.50 & 0.00 \\
52_54.txt & 30819.50 & 0.00 \\
52_55.txt & 34314.00 & 0.00 \\
52_56.txt & 32560.50 & 0.00 \\
52_57.txt & 33396.00 & 0.00 \\
52_58.txt & 34917.60 & 0.00 \\
52_59.txt & 34974.40 & 0.00 \\
52_60.txt & 32927.20 & 0.00 \\
52_61.txt & 95016.20 & 0.00 \\
52_62.txt & 82519.00 & 0.00 \\
52_63.txt & 95121.80 & 0.00 \\
52_64.txt & 76968.60 & 0.00 \\
52_65.txt & 94436.50 & 0.00 \\
52_66.txt & 78219.50 & 0.00 \\
52_67.txt & 96172.00 & 0.00 \\
52_68.txt & 83276.00 & 0.00 \\
52_69.txt & 97995.20 & 0.00 \\
52_70.txt & 80544.00 & 0.00 \\
52_71.txt & 95482.40 & 0.00 \\
52_72.txt & 80340.80 & 0.00 \\
52_73.txt & 53442.80 & 0.00 \\
52_74.txt & 61258.20 & 0.00 \\
52_75.txt & 55140.80 & 0.00 \\
52_76.txt & 61087.80 & 0.00 \\
52_77.txt & 52169.50 & 0.00 \\
52_78.txt & 63800.50 & 0.00 \\
52_79.txt & 52264.50 & 0.00 \\
52_80.txt & 62890.00 & 0.00 \\
52_81.txt & 54639.20 & 0.00 \\
52_82.txt & 66125.60 & 0.00 \\
52_83.txt & 54594.40 & 0.00 \\
52_84.txt & 62833.60 & 0.00 \\
52_85.txt & 64037.20 & 0.00 \\
52_86.txt & 70706.00 & 0.00 \\
52_87.txt & 64782.80 & 0.00 \\
52_88.txt & 70514.20 & 0.00 \\
52_89.txt & 62526.50 & 0.00 \\
52_90.txt & 74100.00 & 0.00 \\
52_91.txt & 70745.00 & 0.00 \\
52_92.txt & 71413.50 & 0.00 \\
52_93.txt & 67470.40 & 0.00 \\
52_94.txt & 73009.60 & 0.00 \\
52_95.txt & 68205.00 & 0.00 \\
52_96.txt & 75558.40 & 0.00 \\
52_97.txt & 124622.00 & 0.00 \\
52_98.txt & 117372.20 & 0.00 \\
52_99.txt & 126929.00 & 0.00 \\
52_100.txt & 115421.40 & 0.00 \\
52_101.txt & 127910.00 & 0.00 \\
52_102.txt & 117109.50 & 0.00 \\
52_103.txt & 130304.50 & 0.00 \\
52_104.txt & 119959.50 & 0.00 \\
52_105.txt & 129011.20 & 0.00 \\
52_106.txt & 118980.00 & 0.00 \\
52_107.txt & 128970.40 & 0.00 \\
52_108.txt & 119152.00 & 0.00 \\
\bottomrule
\end{tabular}
\end{table}

In [9]:
url_file=f"result/lsr_std_mip_feasible_tmax.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval1','bound1','gap1','time1','nodes1','opt1']

table_feasible_tmax = table
table_feasible_tmax

       instance  objval1    bound1  gap1  time1   nodes1  opt1
0      52_1.txt   8710.2   2904.49  0.67   1.68  28593.0     0
1      52_2.txt   8929.6   2665.34  0.70   1.68  27264.0     0
2      52_3.txt   8842.8   2710.63  0.69   1.68  26465.0     0
3      52_4.txt   9305.6   2737.65  0.71   1.68  28149.0     0
4      52_5.txt  10006.0   2969.79  0.70   1.68  27089.0     0
..          ...      ...       ...   ...    ...      ...   ...
103  52_104.txt  37391.5  19482.38  0.48   1.68  32104.0     0
104  52_105.txt  39624.0  20100.23  0.49   1.68  32948.0     0
105  52_106.txt  41639.0  19966.41  0.52   1.68  34785.0     0
106  52_107.txt  39032.0  20923.13  0.46   1.68  34657.0     0
107  52_108.txt  41581.6  19460.79  0.53   1.68  34123.0     0

[108 rows x 7 columns]

In [10]:
latex_table_feasible_tmax = table_feasible_tmax.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMAX segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:melhor_sol_viavel_tmax",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmax)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMAX segundos}
\label{tab:melhor_sol_viavel_tmax}
\begin{tabular}{lrrrrrr}
\toprule
instance & objval1 & bound1 & gap1 & time1 & nodes1 & opt1 \\
\midrule
52_1.txt & 8710.20 & 2904.49 & 0.67 & 1.68 & 28593.00 & 0 \\
52_2.txt & 8929.60 & 2665.34 & 0.70 & 1.68 & 27264.00 & 0 \\
52_3.txt & 8842.80 & 2710.63 & 0.69 & 1.68 & 26465.00 & 0 \\
52_4.txt & 9305.60 & 2737.65 & 0.71 & 1.68 & 28149.00 & 0 \\
52_5.txt & 10006.00 & 2969.79 & 0.70 & 1.68 & 27089.00 & 0 \\
52_6.txt & 10177.50 & 2785.66 & 0.73 & 1.68 & 29227.00 & 0 \\
52_7.txt & 9878.00 & 2972.20 & 0.70 & 1.68 & 24761.00 & 0 \\
52_8.txt & 10207.50 & 2866.06 & 0.72 & 1.68 & 29661.00 & 0 \\
52_9.txt & 10627.20 & 3066.73 & 0.71 & 1.68 & 29624.00 & 0 \\
52_10.txt & 11138.80 & 2990.62 & 0.73 & 1.68 & 26219.00 & 0 \\
52_11.txt & 10377.20 & 3067.44 & 0.70 & 1.68 & 27846.00 & 0 \\
52_12.txt & 10872.20 & 2973.11 & 0.73 & 1.68 & 28043.00 & 0 \\
52_13.txt & 13426.00 & 4991.25 & 0.63 & 1.68 & 24989.00 & 0 \\
52_14.txt & 12556.20 & 4206.81 & 0.66 & 1.68 & 24221.00 & 0 \\
52_15.txt & 13092.60 & 4820.95 & 0.63 & 1.68 & 23170.00 & 0 \\
52_16.txt & 12309.40 & 4356.87 & 0.65 & 1.68 & 26661.00 & 0 \\
52_17.txt & 14518.50 & 5016.88 & 0.65 & 1.68 & 25058.00 & 0 \\
52_18.txt & 13637.50 & 4555.20 & 0.67 & 1.68 & 25822.00 & 0 \\
52_19.txt & 14046.00 & 5130.39 & 0.63 & 1.68 & 22566.00 & 0 \\
52_20.txt & 13832.50 & 4803.68 & 0.65 & 1.68 & 27055.00 & 0 \\
52_21.txt & 15158.80 & 5451.54 & 0.64 & 1.68 & 27795.00 & 0 \\
52_22.txt & 14471.80 & 4838.83 & 0.67 & 1.68 & 29917.00 & 0 \\
52_23.txt & 15020.80 & 5231.68 & 0.65 & 1.68 & 23896.00 & 0 \\
52_24.txt & 14410.60 & 4964.82 & 0.66 & 1.68 & 30428.00 & 0 \\
52_25.txt & 26363.80 & 13224.81 & 0.50 & 1.68 & 24561.00 & 0 \\
52_26.txt & 21717.00 & 10798.49 & 0.50 & 1.68 & 23204.00 & 0 \\
52_27.txt & 24453.60 & 12513.04 & 0.49 & 1.68 & 18903.00 & 0 \\
52_28.txt & 20385.40 & 10812.86 & 0.47 & 1.68 & 26350.00 & 0 \\
52_29.txt & 27038.50 & 13721.98 & 0.49 & 1.68 & 23114.00 & 0 \\
52_30.txt & 23040.00 & 11765.97 & 0.49 & 1.68 & 26864.00 & 0 \\
52_31.txt & 27191.00 & 14289.84 & 0.47 & 1.68 & 24480.00 & 0 \\
52_32.txt & 23824.50 & 11942.24 & 0.50 & 1.68 & 24680.00 & 0 \\
52_33.txt & 28174.20 & 14743.69 & 0.48 & 1.68 & 28278.00 & 0 \\
52_34.txt & 24755.80 & 13297.38 & 0.46 & 1.68 & 28616.00 & 0 \\
52_35.txt & 27241.20 & 15434.23 & 0.43 & 1.68 & 29929.00 & 0 \\
52_36.txt & 24440.40 & 13979.83 & 0.43 & 1.68 & 27645.00 & 0 \\
52_37.txt & 10800.00 & 3806.31 & 0.65 & 1.68 & 31882.00 & 0 \\
52_38.txt & 12147.00 & 4334.19 & 0.64 & 1.68 & 30772.00 & 0 \\
52_39.txt & 10866.80 & 3760.72 & 0.65 & 1.68 & 27923.00 & 0 \\
52_40.txt & 12000.00 & 4095.22 & 0.66 & 1.68 & 30061.00 & 0 \\
52_41.txt & 12456.50 & 4464.48 & 0.64 & 1.68 & 31848.00 & 0 \\
52_42.txt & 14109.00 & 5082.39 & 0.64 & 1.68 & 25238.00 & 0 \\
52_43.txt & 12638.50 & 4351.73 & 0.66 & 1.68 & 27902.00 & 0 \\
52_44.txt & 14055.50 & 5091.05 & 0.64 & 1.68 & 26364.00 & 0 \\
52_45.txt & 13643.80 & 4724.34 & 0.65 & 1.68 & 33078.00 & 0 \\
52_46.txt & 15286.60 & 5573.69 & 0.64 & 1.68 & 31339.00 & 0 \\
52_47.txt & 14016.20 & 4662.63 & 0.67 & 1.68 & 32448.00 & 0 \\
52_48.txt & 15317.00 & 5325.61 & 0.65 & 1.68 & 31210.00 & 0 \\
52_49.txt & 15842.40 & 5834.91 & 0.63 & 1.68 & 27307.00 & 0 \\
52_50.txt & 15810.60 & 5569.21 & 0.65 & 1.68 & 29163.00 & 0 \\
52_51.txt & 15378.40 & 5772.70 & 0.62 & 1.68 & 29768.00 & 0 \\
52_52.txt & 15567.60 & 5674.48 & 0.64 & 1.68 & 29476.00 & 0 \\
52_53.txt & 17153.50 & 6337.03 & 0.63 & 1.68 & 30931.00 & 0 \\
52_54.txt & 17697.50 & 6268.00 & 0.65 & 1.68 & 30752.00 & 0 \\
52_55.txt & 16959.00 & 6384.36 & 0.62 & 1.68 & 30175.00 & 0 \\
52_56.txt & 17737.00 & 5876.71 & 0.67 & 1.68 & 30911.00 & 0 \\
52_57.txt & 18652.40 & 6514.88 & 0.65 & 1.68 & 33747.00 & 0 \\
52_58.txt & 19321.00 & 6480.56 & 0.66 & 1.68 & 32873.00 & 0 \\
52_59.txt & 18232.20 & 6523.85 & 0.64 & 1.68 & 33397.00 & 0 \\
52_60.txt & 19649.00 & 6336.46 & 0.68 & 1.68 & 31243.00 & 0 \\
52_61.txt & 27987.80 & 14163.49 & 0.49 & 1.68 & 22915.00 & 0 \\
52_62.txt & 25580.00 & 12539.98 & 0.51 & 1.68 & 27522.00 & 0 \\
52_63.txt & 27210.80 & 13748.08 & 0.49 & 1.68 & 24233.00 & 0 \\
52_64.txt & 25196.80 & 12440.21 & 0.51 & 1.68 & 26937.00 & 0 \\
52_65.txt & 29715.00 & 14489.76 & 0.51 & 1.68 & 26115.00 & 0 \\
52_66.txt & 27864.00 & 13201.06 & 0.53 & 1.68 & 27182.00 & 0 \\
52_67.txt & 28679.00 & 15475.70 & 0.46 & 1.68 & 25785.00 & 0 \\
52_68.txt & 27651.50 & 14248.40 & 0.48 & 1.68 & 28901.00 & 0 \\
52_69.txt & 31251.00 & 16001.18 & 0.49 & 1.68 & 25158.00 & 0 \\
52_70.txt & 29359.60 & 14707.28 & 0.50 & 1.68 & 30480.00 & 0 \\
52_71.txt & 30222.60 & 16245.30 & 0.46 & 1.68 & 30398.00 & 0 \\
52_72.txt & 28973.60 & 14223.95 & 0.51 & 1.68 & 31332.00 & 0 \\
52_73.txt & 14443.40 & 8966.41 & 0.38 & 1.68 & 33021.00 & 0 \\
52_74.txt & 18385.20 & 10985.27 & 0.40 & 1.68 & 32350.00 & 0 \\
52_75.txt & 15020.00 & 9211.60 & 0.39 & 1.68 & 32074.00 & 0 \\
52_76.txt & 17857.80 & 11055.95 & 0.38 & 1.68 & 31973.00 & 0 \\
52_77.txt & 18733.50 & 10615.94 & 0.43 & 1.68 & 31895.00 & 0 \\
52_78.txt & 23086.00 & 12917.83 & 0.44 & 1.68 & 27466.00 & 0 \\
52_79.txt & 18729.50 & 10598.98 & 0.43 & 1.68 & 32360.00 & 0 \\
52_80.txt & 23350.50 & 13618.84 & 0.42 & 1.68 & 28459.00 & 0 \\
52_81.txt & 20999.80 & 11188.10 & 0.47 & 1.68 & 33386.00 & 0 \\
52_82.txt & 26746.40 & 13861.10 & 0.48 & 1.68 & 28624.00 & 0 \\
52_83.txt & 21399.40 & 11111.88 & 0.48 & 1.68 & 33817.00 & 0 \\
52_84.txt & 26506.60 & 14471.37 & 0.45 & 1.68 & 29096.00 & 0 \\
52_85.txt & 19855.00 & 10553.09 & 0.47 & 1.68 & 31661.00 & 0 \\
52_86.txt & 22868.60 & 12093.87 & 0.47 & 1.68 & 31493.00 & 0 \\
52_87.txt & 20113.60 & 9885.55 & 0.51 & 1.68 & 34825.00 & 0 \\
52_88.txt & 22608.20 & 12210.69 & 0.46 & 1.68 & 34145.00 & 0 \\
52_89.txt & 23134.50 & 12026.11 & 0.48 & 1.68 & 32282.00 & 0 \\
52_90.txt & 27078.50 & 14128.59 & 0.48 & 1.68 & 30562.00 & 0 \\
52_91.txt & 23341.00 & 11874.05 & 0.49 & 1.68 & 33555.00 & 0 \\
52_92.txt & 27220.00 & 13457.86 & 0.51 & 1.68 & 32434.00 & 0 \\
52_93.txt & 26062.20 & 13524.96 & 0.48 & 1.68 & 32708.00 & 0 \\
52_94.txt & 30762.20 & 15482.45 & 0.50 & 1.68 & 30065.00 & 0 \\
52_95.txt & 27101.80 & 13142.80 & 0.52 & 1.68 & 32347.00 & 0 \\
52_96.txt & 30033.20 & 15744.81 & 0.48 & 1.68 & 32650.00 & 0 \\
52_97.txt & 33357.40 & 17831.53 & 0.47 & 1.68 & 29676.00 & 0 \\
52_98.txt & 34024.00 & 17626.93 & 0.48 & 1.68 & 31806.00 & 0 \\
52_99.txt & 33657.00 & 18660.23 & 0.45 & 1.68 & 28195.00 & 0 \\
52_100.txt & 33289.40 & 18663.36 & 0.44 & 1.68 & 28237.00 & 0 \\
52_101.txt & 36588.50 & 19658.16 & 0.46 & 1.68 & 33362.00 & 0 \\
52_102.txt & 38069.00 & 18915.73 & 0.50 & 1.68 & 31405.00 & 0 \\
52_103.txt & 37277.50 & 19673.17 & 0.47 & 1.68 & 31169.00 & 0 \\
52_104.txt & 37391.50 & 19482.38 & 0.48 & 1.68 & 32104.00 & 0 \\
52_105.txt & 39624.00 & 20100.23 & 0.49 & 1.68 & 32948.00 & 0 \\
52_106.txt & 41639.00 & 19966.41 & 0.52 & 1.68 & 34785.00 & 0 \\
52_107.txt & 39032.00 & 20923.13 & 0.46 & 1.68 & 34657.00 & 0 \\
52_108.txt & 41581.60 & 19460.79 & 0.53 & 1.68 & 34123.00 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [11]:
url_file=f"result/lsr_std_mip_feasible_tmean.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval2','bound2','gap2','time2','nodes2','opt2']

table_feasible_tmean = table
table_feasible_tmean

       instance  objval2    bound2  gap2  time2   nodes2  opt2
0      52_1.txt   8846.8   2678.03  0.70   0.65   9333.0     0
1      52_2.txt   9142.2   2461.23  0.73   0.65   9648.0     0
2      52_3.txt   8904.2   2481.87  0.72   0.65   8918.0     0
3      52_4.txt   9353.2   2537.17  0.73   0.65   9299.0     0
4      52_5.txt  10065.0   2721.31  0.73   0.65   9424.0     0
..          ...      ...       ...   ...    ...      ...   ...
103  52_104.txt  37391.5  18222.04  0.51   0.65   8678.0     0
104  52_105.txt  39655.0  18999.20  0.52   0.65  10240.0     0
105  52_106.txt  41639.0  18827.12  0.55   0.65  10962.0     0
106  52_107.txt  39236.4  19855.53  0.49   0.65  10699.0     0
107  52_108.txt  41604.4  18361.96  0.56   0.65  10780.0     0

[108 rows x 7 columns]

In [12]:
latex_table_feasible_tmean = table_feasible_tmean.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMEAN segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:melhor_sol_viavel_tmean",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmean)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMEAN segundos}
\label{tab:melhor_sol_viavel_tmean}
\begin{tabular}{lrrrrrr}
\toprule
instance & objval2 & bound2 & gap2 & time2 & nodes2 & opt2 \\
\midrule
52_1.txt & 8846.80 & 2678.03 & 0.70 & 0.65 & 9333.00 & 0 \\
52_2.txt & 9142.20 & 2461.23 & 0.73 & 0.65 & 9648.00 & 0 \\
52_3.txt & 8904.20 & 2481.87 & 0.72 & 0.65 & 8918.00 & 0 \\
52_4.txt & 9353.20 & 2537.17 & 0.73 & 0.65 & 9299.00 & 0 \\
52_5.txt & 10065.00 & 2721.31 & 0.73 & 0.65 & 9424.00 & 0 \\
52_6.txt & 10383.00 & 2577.83 & 0.75 & 0.65 & 10084.00 & 0 \\
52_7.txt & 9940.50 & 2777.26 & 0.72 & 0.65 & 9263.00 & 0 \\
52_8.txt & 10625.00 & 2627.05 & 0.75 & 0.65 & 10316.00 & 0 \\
52_9.txt & 10725.80 & 2816.60 & 0.74 & 0.65 & 9652.00 & 0 \\
52_10.txt & 11411.20 & 2793.71 & 0.76 & 0.65 & 10574.00 & 0 \\
52_11.txt & 10660.20 & 2824.34 & 0.74 & 0.65 & 10044.00 & 0 \\
52_12.txt & 11060.20 & 2769.70 & 0.75 & 0.65 & 10806.00 & 0 \\
52_13.txt & 13552.80 & 4556.48 & 0.66 & 0.65 & 7790.00 & 0 \\
52_14.txt & 12606.40 & 3897.23 & 0.69 & 0.65 & 9045.00 & 0 \\
52_15.txt & 13324.80 & 4499.53 & 0.66 & 0.65 & 8221.00 & 0 \\
52_16.txt & 12371.60 & 3897.31 & 0.68 & 0.65 & 7620.00 & 0 \\
52_17.txt & 14628.50 & 4547.59 & 0.69 & 0.65 & 8247.00 & 0 \\
52_18.txt & 13649.50 & 4227.93 & 0.69 & 0.65 & 8393.00 & 0 \\
52_19.txt & 14212.00 & 4634.33 & 0.67 & 0.65 & 7960.00 & 0 \\
52_20.txt & 13985.50 & 4376.25 & 0.69 & 0.65 & 9058.00 & 0 \\
52_21.txt & 15158.80 & 4980.33 & 0.67 & 0.65 & 9729.00 & 0 \\
52_22.txt & 14471.80 & 4516.86 & 0.69 & 0.65 & 10298.00 & 0 \\
52_23.txt & 15051.20 & 4779.67 & 0.68 & 0.65 & 9018.00 & 0 \\
52_24.txt & 14576.40 & 4576.43 & 0.69 & 0.65 & 9508.00 & 0 \\
52_25.txt & 26596.60 & 12073.96 & 0.55 & 0.65 & 7671.00 & 0 \\
52_26.txt & 21865.80 & 10068.89 & 0.54 & 0.65 & 7234.00 & 0 \\
52_27.txt & 24710.00 & 11531.60 & 0.53 & 0.65 & 7012.00 & 0 \\
52_28.txt & 21197.20 & 9804.25 & 0.54 & 0.65 & 7640.00 & 0 \\
52_29.txt & 27038.50 & 12551.94 & 0.54 & 0.65 & 8724.00 & 0 \\
52_30.txt & 23040.00 & 10749.91 & 0.53 & 0.65 & 8589.00 & 0 \\
52_31.txt & 27327.00 & 13080.83 & 0.52 & 0.65 & 8531.00 & 0 \\
52_32.txt & 24524.50 & 10791.86 & 0.56 & 0.65 & 9130.00 & 0 \\
52_33.txt & 28260.40 & 13672.68 & 0.52 & 0.65 & 9279.00 & 0 \\
52_34.txt & 24812.80 & 12083.14 & 0.51 & 0.65 & 8863.00 & 0 \\
52_35.txt & 27241.20 & 13741.26 & 0.50 & 0.65 & 8311.00 & 0 \\
52_36.txt & 24507.60 & 12895.25 & 0.47 & 0.65 & 9223.00 & 0 \\
52_37.txt & 11027.00 & 3549.31 & 0.68 & 0.65 & 9533.00 & 0 \\
52_38.txt & 12189.40 & 3996.97 & 0.67 & 0.65 & 9266.00 & 0 \\
52_39.txt & 11030.40 & 3513.54 & 0.68 & 0.65 & 8407.00 & 0 \\
52_40.txt & 12178.80 & 3804.86 & 0.69 & 0.65 & 9151.00 & 0 \\
52_41.txt & 12664.00 & 4064.04 & 0.68 & 0.65 & 8019.00 & 0 \\
52_42.txt & 14245.50 & 4664.11 & 0.67 & 0.65 & 8942.00 & 0 \\
52_43.txt & 12920.00 & 4058.26 & 0.69 & 0.65 & 9804.00 & 0 \\
52_44.txt & 14093.50 & 4650.70 & 0.67 & 0.65 & 8725.00 & 0 \\
52_45.txt & 13643.80 & 4399.06 & 0.68 & 0.65 & 9308.00 & 0 \\
52_46.txt & 15286.60 & 5116.72 & 0.67 & 0.65 & 8344.00 & 0 \\
52_47.txt & 14323.00 & 4299.72 & 0.70 & 0.65 & 9031.00 & 0 \\
52_48.txt & 15643.60 & 4967.94 & 0.68 & 0.65 & 9833.00 & 0 \\
52_49.txt & 16103.20 & 5417.40 & 0.66 & 0.65 & 8987.00 & 0 \\
52_50.txt & 16195.80 & 5177.66 & 0.68 & 0.65 & 9607.00 & 0 \\
52_51.txt & 15495.00 & 5306.82 & 0.66 & 0.65 & 9355.00 & 0 \\
52_52.txt & 15823.80 & 5298.18 & 0.67 & 0.65 & 9596.00 & 0 \\
52_53.txt & 17332.00 & 5957.76 & 0.66 & 0.65 & 10179.00 & 0 \\
52_54.txt & 17771.00 & 5810.51 & 0.67 & 0.65 & 9879.00 & 0 \\
52_55.txt & 17012.00 & 5927.85 & 0.65 & 0.65 & 8781.00 & 0 \\
52_56.txt & 17850.50 & 5388.10 & 0.70 & 0.65 & 8341.00 & 0 \\
52_57.txt & 18808.00 & 6096.12 & 0.68 & 0.65 & 10373.00 & 0 \\
52_58.txt & 19709.40 & 5938.58 & 0.70 & 0.65 & 9183.00 & 0 \\
52_59.txt & 18232.20 & 6038.14 & 0.67 & 0.65 & 10264.00 & 0 \\
52_60.txt & 19758.80 & 5847.01 & 0.70 & 0.65 & 9661.00 & 0 \\
52_61.txt & 28241.80 & 13151.87 & 0.53 & 0.65 & 8232.00 & 0 \\
52_62.txt & 25661.20 & 11841.92 & 0.54 & 0.65 & 8650.00 & 0 \\
52_63.txt & 27605.40 & 12751.51 & 0.54 & 0.65 & 8730.00 & 0 \\
52_64.txt & 25459.40 & 11795.14 & 0.54 & 0.65 & 9447.00 & 0 \\
52_65.txt & 29715.00 & 13268.88 & 0.55 & 0.65 & 8859.00 & 0 \\
52_66.txt & 27962.50 & 12234.71 & 0.56 & 0.65 & 9170.00 & 0 \\
52_67.txt & 28730.50 & 14070.16 & 0.51 & 0.65 & 7849.00 & 0 \\
52_68.txt & 28474.50 & 13115.96 & 0.54 & 0.65 & 8267.00 & 0 \\
52_69.txt & 31251.00 & 15114.10 & 0.52 & 0.65 & 8721.00 & 0 \\
52_70.txt & 29359.60 & 13369.71 & 0.54 & 0.65 & 9100.00 & 0 \\
52_71.txt & 30473.80 & 15222.55 & 0.50 & 0.65 & 10185.00 & 0 \\
52_72.txt & 29593.60 & 12999.75 & 0.56 & 0.65 & 10417.00 & 0 \\
52_73.txt & 14602.60 & 8407.29 & 0.42 & 0.65 & 10560.00 & 0 \\
52_74.txt & 18576.20 & 10236.45 & 0.45 & 0.65 & 9529.00 & 0 \\
52_75.txt & 15078.20 & 8235.27 & 0.45 & 0.65 & 7317.00 & 0 \\
52_76.txt & 17857.80 & 10244.00 & 0.43 & 0.65 & 9838.00 & 0 \\
52_77.txt & 18740.50 & 9733.98 & 0.48 & 0.65 & 9267.00 & 0 \\
52_78.txt & 23234.00 & 11845.66 & 0.49 & 0.65 & 8343.00 & 0 \\
52_79.txt & 18976.50 & 9599.12 & 0.49 & 0.65 & 9233.00 & 0 \\
52_80.txt & 23389.50 & 12347.44 & 0.47 & 0.65 & 7433.00 & 0 \\
52_81.txt & 21058.80 & 10050.31 & 0.52 & 0.65 & 9341.00 & 0 \\
52_82.txt & 26830.60 & 12651.94 & 0.53 & 0.65 & 8565.00 & 0 \\
52_83.txt & 21399.40 & 9913.09 & 0.54 & 0.65 & 7358.00 & 0 \\
52_84.txt & 26565.60 & 12618.30 & 0.53 & 0.65 & 6442.00 & 0 \\
52_85.txt & 19911.00 & 9585.72 & 0.52 & 0.65 & 7345.00 & 0 \\
52_86.txt & 22930.60 & 11141.12 & 0.51 & 0.65 & 8682.00 & 0 \\
52_87.txt & 20223.40 & 9308.45 & 0.54 & 0.65 & 9554.00 & 0 \\
52_88.txt & 22755.20 & 11290.29 & 0.50 & 0.65 & 9412.00 & 0 \\
52_89.txt & 23343.00 & 11004.09 & 0.53 & 0.65 & 9400.00 & 0 \\
52_90.txt & 27677.00 & 12772.56 & 0.54 & 0.65 & 7710.00 & 0 \\
52_91.txt & 23467.00 & 10987.23 & 0.53 & 0.65 & 9362.00 & 0 \\
52_92.txt & 27220.00 & 12147.81 & 0.55 & 0.65 & 5964.00 & 0 \\
52_93.txt & 26316.80 & 12836.51 & 0.51 & 0.65 & 10320.00 & 0 \\
52_94.txt & 30762.20 & 14204.33 & 0.54 & 0.65 & 10166.00 & 0 \\
52_95.txt & 27146.80 & 12256.53 & 0.55 & 0.65 & 9467.00 & 0 \\
52_96.txt & 30033.20 & 14175.21 & 0.53 & 0.65 & 9935.00 & 0 \\
52_97.txt & 33357.40 & 16741.58 & 0.50 & 0.65 & 8138.00 & 0 \\
52_98.txt & 34024.00 & 16609.48 & 0.51 & 0.65 & 8171.00 & 0 \\
52_99.txt & 34366.80 & 17453.17 & 0.49 & 0.65 & 9058.00 & 0 \\
52_100.txt & 33289.40 & 17483.12 & 0.47 & 0.65 & 8841.00 & 0 \\
52_101.txt & 36588.50 & 18522.31 & 0.49 & 0.65 & 10151.00 & 0 \\
52_102.txt & 38184.00 & 17842.64 & 0.53 & 0.65 & 9714.00 & 0 \\
52_103.txt & 37309.50 & 18560.61 & 0.50 & 0.65 & 9648.00 & 0 \\
52_104.txt & 37391.50 & 18222.04 & 0.51 & 0.65 & 8678.00 & 0 \\
52_105.txt & 39655.00 & 18999.20 & 0.52 & 0.65 & 10240.00 & 0 \\
52_106.txt & 41639.00 & 18827.12 & 0.55 & 0.65 & 10962.00 & 0 \\
52_107.txt & 39236.40 & 19855.53 & 0.49 & 0.65 & 10699.00 & 0 \\
52_108.txt & 41604.40 & 18361.96 & 0.56 & 0.65 & 10780.00 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [13]:
table_resume = pd.DataFrame()
table_resume['dif0'] = table_math['fop'] - table_first_feasible['objval0']
table_resume['dif2'] = table_math['fop'] - table_feasible_tmean['objval2']
table_resume['dif1'] = table_math['fop'] - table_feasible_tmax['objval1']
table_resume

        dif0    dif2    dif1
0    -4019.2   -95.2    41.4
1    -3975.0  -289.4   -76.8
2    -4766.6  -272.8  -211.4
3    -4336.8  -276.6  -229.0
4    -4178.0  -306.5  -247.5
..       ...     ...     ...
103 -81559.5  1008.5  1008.5
104 -89911.4  -555.2  -524.2
105 -77046.4   294.6   294.6
106 -89982.2  -248.2   -43.8
107 -78338.8  -791.2  -768.4

[108 rows x 3 columns]

In [14]:
positive_count_dif1 = (table_resume['dif0'] < 0).sum()
positive_count_dif2 = (table_resume['dif2'] < 0).sum()
positive_count_dif3 = (table_resume['dif1'] < 0).sum()
print(f"Ganho do fop em relacao ao mip first feasible: {positive_count_dif1}")
print(f"Ganho do fop em relacao ao mip first feasible tmean: {positive_count_dif2}")
print(f"Ganho do fop em relacao ao mip first feasible tmax: {positive_count_dif3}")

Ganho do fop em relacao ao mip first feasible: 108
Ganho do fop em relacao ao mip first feasible tmean: 74
Ganho do fop em relacao ao mip first feasible tmax: 54

In [15]:
def tabela_mip(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','objval','bound','gap','time','nodes','opt']
    table = table[['instance','bound','objval','gap','time','nodes','opt']]

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'bound':tab['bound'].mean().round(2),
            'objval':tab['objval'].mean().round(2),
            'gap':tab['gap'].mean().round(2),
            'time':tab['time'].mean().round(2),
            'nodes':tab['nodes'].mean().round(2),
            'opt':tab['opt'].sum().round(2),
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [16]:
def tabela_math(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','rf','time_rf','fop','time_fop']
    table['time_total'] = table['time_rf']+table['time_fop']

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'52_{i}.txt'].index,'grupo'] = set_
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'rf':tab['rf'].mean().round(2),
            'time_rf':tab['time_rf'].mean().round(2),
            'fop':tab['fop'].mean().round(2),
            'time_fop':tab['time_fop'].mean().round(2),
            'time_total':tab['time_total'].mean().round(2)
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [17]:
file=f"result/lsr_std_mip_feasible_first.txt"

table_first_feasible_set, table_first_feasible_set_ = tabela_mip(file)

In [18]:
table_first_feasible_set = table_first_feasible_set[['instance','objval','time']]
table_first_feasible_set

  instance     objval  time
0    set01   14754.94   0.0
1    set02   26266.23   0.0
2    set03   81300.89   0.0
3    set04   22182.42   0.0
4    set05   32648.08   0.0
5    set06   88007.67   0.0
6    set07   58353.91   0.0
7    set08   69422.38   0.0
8    set09  122978.48   0.0

In [19]:
latex_table_first_feasible_set = table_first_feasible_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver",  # The caption to appear above the table in the LaTeX document
    label="tab:melhor_sol_viavel_tmean",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_first_feasible_set)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver}
\label{tab:melhor_sol_viavel_tmean}
\begin{tabular}{lrr}
\toprule
instance & objval & time \\
\midrule
set01 & 14754.94 & 0.00 \\
set02 & 26266.23 & 0.00 \\
set03 & 81300.89 & 0.00 \\
set04 & 22182.42 & 0.00 \\
set05 & 32648.08 & 0.00 \\
set06 & 88007.67 & 0.00 \\
set07 & 58353.91 & 0.00 \\
set08 & 69422.38 & 0.00 \\
set09 & 122978.48 & 0.00 \\
\bottomrule
\end{tabular}
\end{table}

In [20]:
file=f"result/lsr_std_mip_feasible_tmax.txt"

table_feasible_tmax_set, table_feasible_tmax_set_ = tabela_mip(file)

In [21]:
table_feasible_tmax_set

  instance     bound    objval   gap  time     nodes  opt
0    set01   2892.48   9922.72  0.71  1.68  27745.08    0
1    set02   4864.08  13873.39  0.65  1.68  25964.83    0
2    set03  13043.70  24885.45  0.48  1.68  25552.00    0
3    set04   4606.03  13111.41  0.65  1.68  30005.42    0
4    set05   6131.10  17333.38  0.64  1.68  30811.92    0
5    set06  14290.37  28307.64  0.49  1.68  27246.50    0
6    set07  11550.27  20438.18  0.43  1.68  31210.08    0
7    set08  12843.74  25014.90  0.49  1.68  32393.92    0
8    set09  19246.84  37127.57  0.48  1.68  31872.25    0

In [22]:
latex_table_feasible_tmax_set = table_feasible_tmax_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMAX segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:melhor_sol_viavel_tmax",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmax_set)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMAX segundos}
\label{tab:melhor_sol_viavel_tmax}
\begin{tabular}{lrrrrrr}
\toprule
instance & bound & objval & gap & time & nodes & opt \\
\midrule
set01 & 2892.48 & 9922.72 & 0.71 & 1.68 & 27745.08 & 0 \\
set02 & 4864.08 & 13873.39 & 0.65 & 1.68 & 25964.83 & 0 \\
set03 & 13043.70 & 24885.45 & 0.48 & 1.68 & 25552.00 & 0 \\
set04 & 4606.03 & 13111.41 & 0.65 & 1.68 & 30005.42 & 0 \\
set05 & 6131.10 & 17333.38 & 0.64 & 1.68 & 30811.92 & 0 \\
set06 & 14290.37 & 28307.64 & 0.49 & 1.68 & 27246.50 & 0 \\
set07 & 11550.27 & 20438.18 & 0.43 & 1.68 & 31210.08 & 0 \\
set08 & 12843.74 & 25014.90 & 0.49 & 1.68 & 32393.92 & 0 \\
set09 & 19246.84 & 37127.57 & 0.48 & 1.68 & 31872.25 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [23]:
file=f"result/lsr_std_mip_feasible_tmean.txt"

table_feasible_tmean_set, table_feasible_tmean_set_ = tabela_mip(file)

table_feasible_tmean_set

  instance     bound    objval   gap  time    nodes  opt
0    set01   2672.18  10093.11  0.74  0.65  9780.08    0
1    set02   4457.50  13965.78  0.68  0.65  8740.58    0
2    set03  11920.46  25093.47  0.53  0.65  8350.58    0
3    set04   4257.10  13270.47  0.68  0.65  9030.25    0
4    set05   5683.68  17507.64  0.68  0.65  9517.17    0
5    set06  13244.69  28544.02  0.54  0.65  8968.92    0
6    set07  10490.24  20525.81  0.48  0.65  8602.17    0
7    set08  11809.15  25148.85  0.53  0.65  8943.08    0
8    set09  18123.23  37220.49  0.51  0.65  9590.00    0

In [24]:
latex_table_feasible_tmean_set = table_feasible_tmean_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMEAN segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:melhor_sol_viavel_tmean",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmean_set)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMEAN segundos}
\label{tab:melhor_sol_viavel_tmean}
\begin{tabular}{lrrrrrr}
\toprule
instance & bound & objval & gap & time & nodes & opt \\
\midrule
set01 & 2672.18 & 10093.11 & 0.74 & 0.65 & 9780.08 & 0 \\
set02 & 4457.50 & 13965.78 & 0.68 & 0.65 & 8740.58 & 0 \\
set03 & 11920.46 & 25093.47 & 0.53 & 0.65 & 8350.58 & 0 \\
set04 & 4257.10 & 13270.47 & 0.68 & 0.65 & 9030.25 & 0 \\
set05 & 5683.68 & 17507.64 & 0.68 & 0.65 & 9517.17 & 0 \\
set06 & 13244.69 & 28544.02 & 0.54 & 0.65 & 8968.92 & 0 \\
set07 & 10490.24 & 20525.81 & 0.48 & 0.65 & 8602.17 & 0 \\
set08 & 11809.15 & 25148.85 & 0.53 & 0.65 & 8943.08 & 0 \\
set09 & 18123.23 & 37220.49 & 0.51 & 0.65 & 9590.00 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [25]:
file=f"result/lsr_std_math.txt"

table_math_set, table_math_set_ = tabela_math(file)

In [26]:
table_math_set

  instance        rf  time_rf       fop  time_fop  time_total
0    set01   9856.98     0.53   9780.79      0.89        1.42
1    set02  13979.71     0.32  13671.12      0.41        0.73
2    set03  26252.88     0.21  25008.06      0.16        0.37
3    set04  13128.09     0.36  13009.17      0.49        0.85
4    set05  17366.63     0.34  17100.82      0.51        0.85
5    set06  29714.86     0.22  28358.95      0.17        0.39
6    set07  21004.72     0.21  20639.34      0.21        0.42
7    set08  25575.98     0.21  25174.50      0.25        0.45
8    set09  39140.93     0.19  37463.98      0.18        0.37

In [27]:
latex_table_math_set = table_math_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Solução viável encontrada pelo RF+FOP",  # The caption to appear above the table in the LaTeX document
    label="tab:sol_math",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_math_set)

\begin{table}[htbp]
\caption{Solução viável encontrada pelo RF+FOP}
\label{tab:sol_math}
\begin{tabular}{lrrrrrr}
\toprule
instance & rf & time_rf & fop & time_fop & time_total \\
\midrule
set01 & 9856.98 & 0.53 & 9780.79 & 0.89 & 1.42 \\
set02 & 13979.71 & 0.32 & 13671.12 & 0.41 & 0.73 \\
set03 & 26252.88 & 0.21 & 25008.06 & 0.16 & 0.37 \\
set04 & 13128.09 & 0.36 & 13009.17 & 0.49 & 0.85 \\
set05 & 17366.63 & 0.34 & 17100.82 & 0.51 & 0.85 \\
set06 & 29714.86 & 0.22 & 28358.95 & 0.17 & 0.39 \\
set07 & 21004.72 & 0.21 & 20639.34 & 0.21 & 0.42 \\
set08 & 25575.98 & 0.21 & 25174.50 & 0.25 & 0.45 \\
set09 & 39140.93 & 0.19 & 37463.98 & 0.18 & 0.37 \\
\bottomrule
\end{tabular}
\end{table}

In [28]:
file=f"result/lsr_std_mip.txt"

table_mip_set, table_mip_set_ = tabela_mip(file)
table_mip_set

  instance     bound    objval  gap    time      nodes  opt
0    set01   9674.50   9680.20  0.0  419.51  723210.67   11
1    set02  13530.83  13530.83  0.0  161.10  281019.25   12
2    set03  24430.29  24430.29  0.0   19.24   25153.83   12
3    set04  12843.64  12843.64  0.0   10.76   21227.25   12
4    set05  16826.48  16826.48  0.0  123.93  226197.33   12
5    set06  27706.90  27706.90  0.0   35.28   43102.75   12
6    set07  20334.82  20334.82  0.0    1.41    1795.92   12
7    set08  24661.75  24661.75  0.0    2.18    2259.50   12
8    set09  36360.38  36360.38  0.0    4.40    3224.17   12

In [29]:
latex_table_mip_set = table_mip_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Soluções encontradas pelo solver",  # The caption to appear above the table in the LaTeX document
    label="tab:sol_mip",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_mip_set)

\begin{table}[htbp]
\caption{Soluções encontradas pelo solver}
\label{tab:sol_mip}
\begin{tabular}{lrrrrrr}
\toprule
instance & bound & objval & gap & time & nodes & opt \\
\midrule
set01 & 9674.50 & 9680.20 & 0.00 & 419.51 & 723210.67 & 11 \\
set02 & 13530.83 & 13530.83 & 0.00 & 161.10 & 281019.25 & 12 \\
set03 & 24430.29 & 24430.29 & 0.00 & 19.24 & 25153.83 & 12 \\
set04 & 12843.64 & 12843.64 & 0.00 & 10.76 & 21227.25 & 12 \\
set05 & 16826.48 & 16826.48 & 0.00 & 123.93 & 226197.33 & 12 \\
set06 & 27706.90 & 27706.90 & 0.00 & 35.28 & 43102.75 & 12 \\
set07 & 20334.82 & 20334.82 & 0.00 & 1.41 & 1795.92 & 12 \\
set08 & 24661.75 & 24661.75 & 0.00 & 2.18 & 2259.50 & 12 \\
set09 & 36360.38 & 36360.38 & 0.00 & 4.40 & 3224.17 & 12 \\
\bottomrule
\end{tabular}
\end{table}

In [30]:
file=f"result/lsr_std_mip.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

tab = pd.DataFrame()
tab = pd.concat([tab, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

tab_mip = tab
tab_mip

       instance     bound    objval  gap    time      nodes  opt
0      52_1.txt   8698.80   8698.80  0.0   12.09   20827.00    1
1      52_2.txt   8781.80   8781.80  0.0   35.71   92569.00    1
2      52_3.txt   8541.60   8541.60  0.0    4.37    8093.00    1
3      52_4.txt   8943.80   8943.80  0.0   36.89   95366.00    1
4      52_5.txt   9717.00   9717.00  0.0  201.02  392059.00    1
..          ...       ...       ...  ...     ...        ...  ...
104  52_105.txt  38622.80  38622.80  0.0    4.66    3592.00    1
105  52_106.txt  40310.40  40310.40  0.0   10.80    8824.00    1
106  52_107.txt  38611.20  38611.20  0.0    5.00    4076.00    1
107  52_108.txt  39826.20  39826.20  0.0    3.25    2114.00    1
108      resume  20708.37  20707.73  0.0   86.42  147465.63  107

[109 rows x 7 columns]

In [31]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set01']
)

set01_mip = tab
#set01_mip

In [32]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set02']
)

set02_mip = tab
#set02_mip

In [33]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set03']
)

set03_mip = tab
#set03_mip

In [34]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set04']
)


set04_mip = tab
#set04_mip

In [35]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set05']
)

set05_mip = tab
#set05_mip

In [36]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set06']
)

set06_mip = tab
#set06_mip

In [37]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set07']
)

set07_mip = tab
#set07_mip

In [38]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set08']
)

set08_mip = tab
#set08_mip

In [39]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,109):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set09']
)

set09_mip = tab
#set09_mip

In [40]:
res_mip = pd.DataFrame()
res_mip = pd.concat([res_mip,set01_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set02_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set03_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set04_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set05_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set06_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set07_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set08_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set09_mip], ignore_index= True)
#res_mip

In [41]:
tab = pd.DataFrame({
    'instance':f'res_mip',
    'bound':res_mip['bound'].mean(),
    'objval':res_mip['objval'].mean(),
    'gap':res_mip['gap'].mean(),
    'time':res_mip['time'].mean(),
    'nodes':res_mip['nodes'].mean(),
    'opt':res_mip['opt'].sum(),
    },index=[f'res_mip']
)

res_mip = pd.concat([res_mip, tab], ignore_index=True)
res_mip

#print(res_mip[['instance','objval','bound','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

,instance,bound,objval,gap,time,nodes,opt
0,set01,9680.200000,9674.500000,0.000833,419.507500,723210.666667,11
1,set02,13530.833333,13530.833333,0.000000,161.103333,281019.250000,12
2,set03,24430.291667,24430.291667,0.000000,19.242500,25153.833333,12
3,set04,12843.641667,12843.641667,0.000000,10.765000,21227.250000,12
4,set05,16826.475000,16826.475000,0.000000,123.930000,226197.333333,12
5,set06,27706.900000,27706.900000,0.000000,35.277500,43102.750000,12
6,set07,20334.816667,20334.816667,0.000000,1.412500,1795.916667,12
7,set08,24661.750000,24661.750000,0.000000,2.180833,2259.500000,12
8,set09,36360.383333,36360.383333,0.000000,4.395833,3224.166667,12
9,res_mip,20708.365741,20707.732407,0.000093,86.423889,147465.629630,107