In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [43]:
url_file=f"std_math/result/clsr_std_math.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','rf','time_rf','fop','time_fop']
table['time_total'] = table['time_rf']+table['time_fop']

table = pd.DataFrame({
    'instance':f'resume',
    'rf':table['rf'].mean().round(2),
    'time_rf':table['time_rf'].mean().round(2),
    'fop':table['fop'].mean().round(2),
    'time_fop':table['time_fop'].mean().round(2),
    'time_total':table['time_total'].mean().round(2),
    },index=[f'math']
)

table_math = table
table_math

     instance        rf  time_rf       fop  time_fop  time_total
math   resume  35784.51     0.25  34298.97      0.19        0.44

In [44]:
latex_table_math = table_math.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Solução viável encontrada pela matheuristica RF+FOP",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_sol_viavel_rf_fop",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_math)

\begin{table}[htbp]
\caption{Solução viável encontrada pela matheuristica RF+FOP}
\label{tab:clsr_sol_viavel_rf_fop}
\begin{tabular}{lrrrrr}
\toprule
instance & rf & time_rf & fop & time_fop & time_total \\
\midrule
resume & 35784.51 & 0.25 & 34298.97 & 0.19 & 0.44 \\
\bottomrule
\end{tabular}
\end{table}

In [45]:
print(table_math['time_total'].max())
print(table_math['time_total'].mean())

0.44
0.44

In [5]:
url_file=f"std_mip/result/clsr_std_mip_first_feasible.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval0','bound0','gap0','time0','nodes0','opt0']

table_first_feasible = table
table_first_feasible = table_first_feasible[['instance','objval0','time0']]
table_first_feasible

        instance   objval0  time0
0      c52_1.txt   12770.8    0.0
1      c52_2.txt   12827.8    0.0
2      c52_3.txt   13398.0    0.0
3      c52_4.txt   14070.0    0.0
4      c52_5.txt   13936.5    0.0
..           ...       ...    ...
103  c52_104.txt  118984.5    0.0
104  c52_105.txt  129011.2    0.0
105  c52_106.txt  118980.0    0.0
106  c52_107.txt  128970.4    0.0
107  c52_108.txt  119152.0    0.0

[108 rows x 3 columns]

In [6]:
latex_table = table_first_feasible.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Primeira solução viável encontrada pelo solver",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_primeira_sol_viavel_solver",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table)

\begin{table}[htbp]
\caption{Primeira solução viável encontrada pelo solver}
\label{tab:clsr_primeira_sol_viavel_solver}
\begin{tabular}{lrr}
\toprule
instance & objval0 & time0 \\
\midrule
c52_1.txt & 12770.80 & 0.00 \\
c52_2.txt & 12827.80 & 0.00 \\
c52_3.txt & 13398.00 & 0.00 \\
c52_4.txt & 14070.00 & 0.00 \\
c52_5.txt & 13936.50 & 0.00 \\
c52_6.txt & 15513.00 & 0.00 \\
c52_7.txt & 14379.50 & 0.00 \\
c52_8.txt & 15175.50 & 0.00 \\
c52_9.txt & 15432.80 & 0.00 \\
c52_10.txt & 17183.20 & 0.00 \\
c52_11.txt & 16616.00 & 0.00 \\
c52_12.txt & 16412.80 & 0.00 \\
c52_13.txt & 27121.00 & 0.00 \\
c52_14.txt & 22392.60 & 0.00 \\
c52_15.txt & 26663.60 & 0.00 \\
c52_16.txt & 23064.00 & 0.00 \\
c52_17.txt & 27831.50 & 0.00 \\
c52_18.txt & 23954.50 & 0.00 \\
c52_19.txt & 28477.00 & 0.00 \\
c52_20.txt & 26126.00 & 0.00 \\
c52_21.txt & 29276.00 & 0.00 \\
c52_22.txt & 24865.60 & 0.00 \\
c52_23.txt & 26995.00 & 0.00 \\
c52_24.txt & 28591.80 & 0.00 \\
c52_25.txt & 90899.80 & 0.00 \\
c52_26.txt & 70697.00 & 0.00 \\
c52_27.txt & 87234.60 & 0.00 \\
c52_28.txt & 65796.20 & 0.00 \\
c52_29.txt & 91919.50 & 0.00 \\
c52_30.txt & 71556.00 & 0.00 \\
c52_31.txt & 92936.50 & 0.00 \\
c52_32.txt & 71046.00 & 0.00 \\
c52_33.txt & 95331.20 & 0.00 \\
c52_34.txt & 70328.00 & 0.00 \\
c52_35.txt & 89682.00 & 0.00 \\
c52_36.txt & 72782.40 & 0.00 \\
c52_37.txt & 20826.80 & 0.00 \\
c52_38.txt & 20420.60 & 0.00 \\
c52_39.txt & 19578.80 & 0.00 \\
c52_40.txt & 20945.60 & 0.00 \\
c52_41.txt & 21114.00 & 0.00 \\
c52_42.txt & 24287.50 & 0.00 \\
c52_43.txt & 21623.00 & 0.00 \\
c52_44.txt & 23064.00 & 0.00 \\
c52_45.txt & 21563.20 & 0.00 \\
c52_46.txt & 25384.80 & 0.00 \\
c52_47.txt & 23000.00 & 0.00 \\
c52_48.txt & 25631.20 & 0.00 \\
c52_49.txt & 32185.20 & 0.00 \\
c52_50.txt & 29632.40 & 0.00 \\
c52_51.txt & 35012.60 & 0.00 \\
c52_52.txt & 29698.80 & 0.00 \\
c52_53.txt & 33452.50 & 0.00 \\
c52_54.txt & 30819.50 & 0.00 \\
c52_55.txt & 34314.00 & 0.00 \\
c52_56.txt & 32560.50 & 0.00 \\
c52_57.txt & 33396.00 & 0.00 \\
c52_58.txt & 34917.60 & 0.00 \\
c52_59.txt & 34871.60 & 0.00 \\
c52_60.txt & 33708.60 & 0.00 \\
c52_61.txt & 95016.20 & 0.00 \\
c52_62.txt & 82519.00 & 0.00 \\
c52_63.txt & 95121.80 & 0.00 \\
c52_64.txt & 78944.20 & 0.00 \\
c52_65.txt & 94436.50 & 0.00 \\
c52_66.txt & 78219.50 & 0.00 \\
c52_67.txt & 94831.50 & 0.00 \\
c52_68.txt & 83276.00 & 0.00 \\
c52_69.txt & 97995.20 & 0.00 \\
c52_70.txt & 80544.00 & 0.00 \\
c52_71.txt & 99396.00 & 0.00 \\
c52_72.txt & 76450.40 & 0.00 \\
c52_73.txt & 53442.80 & 0.00 \\
c52_74.txt & 61258.20 & 0.00 \\
c52_75.txt & 53505.40 & 0.00 \\
c52_76.txt & 59829.80 & 0.00 \\
c52_77.txt & 52169.50 & 0.00 \\
c52_78.txt & 63800.50 & 0.00 \\
c52_79.txt & 52264.50 & 0.00 \\
c52_80.txt & 70145.00 & 0.00 \\
c52_81.txt & 54639.20 & 0.00 \\
c52_82.txt & 66125.60 & 0.00 \\
c52_83.txt & 56836.00 & 0.00 \\
c52_84.txt & 63770.40 & 0.00 \\
c52_85.txt & 64037.20 & 0.00 \\
c52_86.txt & 70706.00 & 0.00 \\
c52_87.txt & 64782.80 & 0.00 \\
c52_88.txt & 69292.00 & 0.00 \\
c52_89.txt & 62526.50 & 0.00 \\
c52_90.txt & 74100.00 & 0.00 \\
c52_91.txt & 70671.50 & 0.00 \\
c52_92.txt & 71413.50 & 0.00 \\
c52_93.txt & 67470.40 & 0.00 \\
c52_94.txt & 73009.60 & 0.00 \\
c52_95.txt & 65461.60 & 0.00 \\
c52_96.txt & 75753.00 & 0.00 \\
c52_97.txt & 124622.00 & 0.00 \\
c52_98.txt & 117372.20 & 0.00 \\
c52_99.txt & 125329.80 & 0.00 \\
c52_100.txt & 115421.40 & 0.00 \\
c52_101.txt & 127910.00 & 0.00 \\
c52_102.txt & 117109.50 & 0.00 \\
c52_103.txt & 128962.50 & 0.00 \\
c52_104.txt & 118984.50 & 0.00 \\
c52_105.txt & 129011.20 & 0.00 \\
c52_106.txt & 118980.00 & 0.00 \\
c52_107.txt & 128970.40 & 0.00 \\
c52_108.txt & 119152.00 & 0.00 \\
\bottomrule
\end{tabular}
\end{table}

In [7]:
url_file=f"std_mip/result/clsr_std_mip_tmax.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval1','bound1','gap','time1','nodes1','opt1']

table_feasible_tmax = table
table_feasible_tmax

        instance  objval1    bound1   gap  time1  nodes1  opt1
0      c52_1.txt   9944.2   9373.67  0.06   0.72   586.0     0
1      c52_2.txt  10451.8   9648.45  0.08   0.72   593.0     0
2      c52_3.txt   9531.8   9114.59  0.04   0.72   634.0     0
3      c52_4.txt  10490.6   9981.14  0.05   0.72   591.0     0
4      c52_5.txt  11401.5  10862.21  0.05   0.72   614.0     0
..           ...      ...       ...   ...    ...     ...   ...
103  c52_104.txt  74643.5  71405.23  0.04   0.72   591.0     0
104  c52_105.txt  71762.0  69203.89  0.04   0.72   595.0     0
105  c52_106.txt  84605.4  81387.01  0.04   0.72   604.0     0
106  c52_107.txt  66024.0  62172.95  0.06   0.72   600.0     0
107  c52_108.txt  69579.6  65173.51  0.06   0.72   578.0     0

[108 rows x 7 columns]

In [8]:
latex_table_feasible_tmax = table_feasible_tmax.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMAX segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_melhor_sol_viavel_tmax",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmax)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMAX segundos}
\label{tab:clsr_melhor_sol_viavel_tmax}
\begin{tabular}{lrrrrrr}
\toprule
instance & objval1 & bound1 & gap & time1 & nodes1 & opt1 \\
\midrule
c52_1.txt & 9944.20 & 9373.67 & 0.06 & 0.72 & 586.00 & 0 \\
c52_2.txt & 10451.80 & 9648.45 & 0.08 & 0.72 & 593.00 & 0 \\
c52_3.txt & 9531.80 & 9114.59 & 0.04 & 0.72 & 634.00 & 0 \\
c52_4.txt & 10490.60 & 9981.14 & 0.05 & 0.72 & 591.00 & 0 \\
c52_5.txt & 11401.50 & 10862.21 & 0.05 & 0.72 & 614.00 & 0 \\
c52_6.txt & 11347.50 & 10389.50 & 0.08 & 0.72 & 589.00 & 0 \\
c52_7.txt & 10328.00 & 9974.94 & 0.03 & 0.72 & 624.00 & 0 \\
c52_8.txt & 10757.50 & 10057.32 & 0.07 & 0.72 & 582.00 & 0 \\
c52_9.txt & 11721.40 & 11132.58 & 0.05 & 0.72 & 604.00 & 0 \\
c52_10.txt & 11837.20 & 10932.01 & 0.08 & 0.72 & 584.00 & 0 \\
c52_11.txt & 11249.80 & 10741.84 & 0.05 & 0.72 & 621.00 & 0 \\
c52_12.txt & 11745.40 & 10739.65 & 0.09 & 0.72 & 580.00 & 0 \\
c52_13.txt & 18510.60 & 17800.36 & 0.04 & 0.72 & 653.00 & 0 \\
c52_14.txt & 15226.00 & 13745.97 & 0.10 & 0.72 & 585.00 & 0 \\
c52_15.txt & 17696.00 & 16480.32 & 0.07 & 0.72 & 624.00 & 0 \\
c52_16.txt & 16072.00 & 15112.06 & 0.06 & 0.72 & 586.00 & 0 \\
c52_17.txt & 19357.00 & 18442.78 & 0.05 & 0.72 & 618.00 & 0 \\
c52_18.txt & 16491.50 & 15024.22 & 0.09 & 0.72 & 583.00 & 0 \\
c52_19.txt & 17825.00 & 16984.99 & 0.05 & 0.72 & 622.00 & 0 \\
c52_20.txt & 18741.00 & 17451.47 & 0.07 & 0.72 & 580.00 & 0 \\
c52_21.txt & 20251.60 & 19207.19 & 0.05 & 0.72 & 634.00 & 0 \\
c52_22.txt & 17941.60 & 16083.24 & 0.10 & 0.72 & 592.00 & 0 \\
c52_23.txt & 17797.60 & 16757.95 & 0.06 & 0.72 & 746.00 & 0 \\
c52_24.txt & 17075.00 & 15836.62 & 0.07 & 0.72 & 591.00 & 0 \\
c52_25.txt & 52170.00 & 49447.78 & 0.05 & 0.72 & 594.00 & 0 \\
c52_26.txt & 45410.40 & 42437.08 & 0.07 & 0.72 & 597.00 & 0 \\
c52_27.txt & 48392.20 & 46751.37 & 0.03 & 0.72 & 586.00 & 0 \\
c52_28.txt & 43194.80 & 40933.87 & 0.05 & 0.72 & 599.00 & 0 \\
c52_29.txt & 51579.28 & 49076.80 & 0.05 & 0.72 & 598.00 & 0 \\
c52_30.txt & 46435.50 & 43310.96 & 0.07 & 0.72 & 580.00 & 0 \\
c52_31.txt & 62917.50 & 60078.63 & 0.05 & 0.72 & 633.00 & 0 \\
c52_32.txt & 42728.00 & 39676.50 & 0.07 & 0.72 & 591.00 & 0 \\
c52_33.txt & 53454.40 & 50930.43 & 0.05 & 0.72 & 593.00 & 0 \\
c52_34.txt & 44952.40 & 41804.43 & 0.07 & 0.72 & 588.00 & 0 \\
c52_35.txt & 57464.00 & 55908.75 & 0.03 & 0.72 & 672.00 & 0 \\
c52_36.txt & 41331.20 & 39061.80 & 0.05 & 0.72 & 606.00 & 0 \\
c52_37.txt & 13994.40 & 13406.29 & 0.04 & 0.72 & 682.00 & 0 \\
c52_38.txt & 15785.60 & 14838.73 & 0.06 & 0.72 & 591.00 & 0 \\
c52_39.txt & 12727.00 & 12303.03 & 0.03 & 0.72 & 651.00 & 0 \\
c52_40.txt & 14165.20 & 13400.87 & 0.05 & 0.72 & 600.00 & 0 \\
c52_41.txt & 13755.50 & 12824.31 & 0.07 & 0.72 & 607.00 & 0 \\
c52_42.txt & 16703.00 & 15441.62 & 0.08 & 0.72 & 593.00 & 0 \\
c52_43.txt & 14407.00 & 13647.73 & 0.05 & 0.72 & 634.00 & 0 \\
c52_44.txt & 16146.00 & 15156.44 & 0.06 & 0.72 & 601.00 & 0 \\
c52_45.txt & 14824.40 & 14107.57 & 0.05 & 0.72 & 588.00 & 0 \\
c52_46.txt & 17590.60 & 16559.97 & 0.06 & 0.72 & 614.00 & 0 \\
c52_47.txt & 15019.20 & 14624.67 & 0.03 & 0.72 & 648.00 & 0 \\
c52_48.txt & 17529.00 & 16801.67 & 0.04 & 0.72 & 612.00 & 0 \\
c52_49.txt & 20971.20 & 18977.85 & 0.10 & 0.72 & 576.00 & 0 \\
c52_50.txt & 22557.80 & 20961.05 & 0.07 & 0.72 & 595.00 & 0 \\
c52_51.txt & 23341.60 & 22234.20 & 0.05 & 0.72 & 645.00 & 0 \\
c52_52.txt & 22294.60 & 20672.52 & 0.07 & 0.72 & 586.00 & 0 \\
c52_53.txt & 21526.50 & 19368.07 & 0.10 & 0.72 & 563.00 & 0 \\
c52_54.txt & 22643.00 & 21191.76 & 0.06 & 0.72 & 577.00 & 0 \\
c52_55.txt & 20639.00 & 19467.01 & 0.06 & 0.72 & 616.00 & 0 \\
c52_56.txt & 21983.50 & 19878.14 & 0.10 & 0.72 & 578.00 & 0 \\
c52_57.txt & 24992.60 & 23155.86 & 0.07 & 0.72 & 607.00 & 0 \\
c52_58.txt & 25020.00 & 22761.75 & 0.09 & 0.72 & 582.00 & 0 \\
c52_59.txt & 22499.80 & 21346.89 & 0.05 & 0.72 & 638.00 & 0 \\
c52_60.txt & 23721.00 & 21657.72 & 0.09 & 0.72 & 585.00 & 0 \\
c52_61.txt & 57343.00 & 55029.11 & 0.04 & 0.72 & 581.00 & 0 \\
c52_62.txt & 46550.80 & 44200.82 & 0.05 & 0.72 & 587.00 & 0 \\
c52_63.txt & 51097.20 & 48783.04 & 0.05 & 0.72 & 589.00 & 0 \\
c52_64.txt & 50845.20 & 49312.76 & 0.03 & 0.72 & 595.00 & 0 \\
c52_65.txt & 63401.50 & 61398.30 & 0.03 & 0.72 & 626.00 & 0 \\
c52_66.txt & 50779.00 & 46490.22 & 0.08 & 0.72 & 584.00 & 0 \\
c52_67.txt & 58580.50 & 56311.50 & 0.04 & 0.72 & 651.00 & 0 \\
c52_68.txt & 49183.50 & 45387.28 & 0.08 & 0.72 & 593.00 & 0 \\
c52_69.txt & 60312.00 & 57078.14 & 0.05 & 0.72 & 597.00 & 0 \\
c52_70.txt & 49856.40 & 45681.70 & 0.08 & 0.72 & 587.00 & 0 \\
c52_71.txt & 62948.00 & 60204.09 & 0.04 & 0.72 & 647.00 & 0 \\
c52_72.txt & 49497.00 & 46784.26 & 0.05 & 0.72 & 587.00 & 0 \\
c52_73.txt & 16923.60 & 16923.60 & 0.00 & 0.10 & 192.00 & 1 \\
c52_74.txt & 22493.80 & 22493.80 & 0.00 & 0.07 & 68.00 & 1 \\
c52_75.txt & 17905.80 & 17905.80 & 0.00 & 0.03 & 10.00 & 1 \\
c52_76.txt & 22717.80 & 22717.80 & 0.00 & 0.04 & 1.00 & 1 \\
c52_77.txt & 23991.00 & 23878.63 & 0.00 & 0.72 & 916.00 & 0 \\
c52_78.txt & 34161.50 & 33818.99 & 0.01 & 0.72 & 958.00 & 0 \\
c52_79.txt & 23348.50 & 23198.65 & 0.01 & 0.72 & 1159.00 & 0 \\
c52_80.txt & 37338.00 & 37142.53 & 0.01 & 0.72 & 1176.00 & 0 \\
c52_81.txt & 25011.80 & 24390.13 & 0.02 & 0.72 & 738.00 & 0 \\
c52_82.txt & 42178.20 & 41080.48 & 0.03 & 0.72 & 668.00 & 0 \\
c52_83.txt & 29905.00 & 29600.20 & 0.01 & 0.72 & 1494.00 & 0 \\
c52_84.txt & 37894.60 & 36824.09 & 0.03 & 0.72 & 815.00 & 0 \\
c52_85.txt & 28188.40 & 28188.40 & 0.00 & 0.60 & 1641.00 & 1 \\
c52_86.txt & 33886.80 & 33886.80 & 0.00 & 0.56 & 1476.00 & 1 \\
c52_87.txt & 27593.80 & 27593.80 & 0.00 & 0.53 & 1473.00 & 1 \\
c52_88.txt & 34623.00 & 34623.00 & 0.00 & 0.16 & 368.00 & 1 \\
c52_89.txt & 34412.50 & 33333.85 & 0.03 & 0.72 & 693.00 & 0 \\
c52_90.txt & 42968.00 & 41980.53 & 0.02 & 0.72 & 671.00 & 0 \\
c52_91.txt & 33227.00 & 32870.22 & 0.01 & 0.72 & 1165.00 & 0 \\
c52_92.txt & 39111.00 & 38103.34 & 0.03 & 0.72 & 665.00 & 0 \\
c52_93.txt & 39894.20 & 38813.01 & 0.03 & 0.72 & 647.00 & 0 \\
c52_94.txt & 45737.00 & 43766.91 & 0.04 & 0.72 & 601.00 & 0 \\
c52_95.txt & 36475.60 & 35078.83 & 0.04 & 0.72 & 619.00 & 0 \\
c52_96.txt & 49859.80 & 48547.77 & 0.03 & 0.72 & 600.00 & 0 \\
c52_97.txt & 68682.60 & 65494.32 & 0.05 & 0.72 & 597.00 & 0 \\
c52_98.txt & 84066.60 & 82174.74 & 0.02 & 0.72 & 603.00 & 0 \\
c52_99.txt & 75572.20 & 73208.52 & 0.03 & 0.72 & 627.00 & 0 \\
c52_100.txt & 67904.80 & 65520.27 & 0.04 & 0.72 & 595.00 & 0 \\
c52_101.txt & 75074.50 & 71020.61 & 0.05 & 0.72 & 605.00 & 0 \\
c52_102.txt & 83706.00 & 80107.78 & 0.04 & 0.72 & 610.00 & 0 \\
c52_103.txt & 73212.50 & 70441.77 & 0.04 & 0.72 & 779.00 & 0 \\
c52_104.txt & 74643.50 & 71405.23 & 0.04 & 0.72 & 591.00 & 0 \\
c52_105.txt & 71762.00 & 69203.89 & 0.04 & 0.72 & 595.00 & 0 \\
c52_106.txt & 84605.40 & 81387.01 & 0.04 & 0.72 & 604.00 & 0 \\
c52_107.txt & 66024.00 & 62172.95 & 0.06 & 0.72 & 600.00 & 0 \\
c52_108.txt & 69579.60 & 65173.51 & 0.06 & 0.72 & 578.00 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [9]:
url_file=f"std_mip/result/clsr_std_mip_tmean.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval2','bound2','gap2','time2','nodes2','opt2']

table_feasible_tmean = table
table_feasible_tmean

        instance  objval2    bound2  gap2  time2  nodes2  opt2
0      c52_1.txt   9944.2   9221.21  0.07   0.44   557.0     0
1      c52_2.txt  10451.8   9500.75  0.09   0.44   563.0     0
2      c52_3.txt   9531.8   9062.38  0.05   0.44   593.0     0
3      c52_4.txt  10490.6   9905.24  0.06   0.44   560.0     0
4      c52_5.txt  11401.5  10806.61  0.05   0.44   574.0     0
..           ...      ...       ...   ...    ...     ...   ...
103  c52_104.txt  74643.5  71316.81  0.04   0.44   574.0     0
104  c52_105.txt  72160.4  68995.19  0.04   0.44   567.0     0
105  c52_106.txt  84605.4  81276.05  0.04   0.44   580.0     0
106  c52_107.txt  66024.0  62038.47  0.06   0.44   575.0     0
107  c52_108.txt  69579.6  65015.97  0.07   0.44   555.0     0

[108 rows x 7 columns]

In [10]:
latex_table_feasible_tmean = table_feasible_tmean.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMEAN segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_melhor_sol_viavel_tmean",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmean)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMEAN segundos}
\label{tab:clsr_melhor_sol_viavel_tmean}
\begin{tabular}{lrrrrrr}
\toprule
instance & objval2 & bound2 & gap2 & time2 & nodes2 & opt2 \\
\midrule
c52_1.txt & 9944.20 & 9221.21 & 0.07 & 0.44 & 557.00 & 0 \\
c52_2.txt & 10451.80 & 9500.75 & 0.09 & 0.44 & 563.00 & 0 \\
c52_3.txt & 9531.80 & 9062.38 & 0.05 & 0.44 & 593.00 & 0 \\
c52_4.txt & 10490.60 & 9905.24 & 0.06 & 0.44 & 560.00 & 0 \\
c52_5.txt & 11401.50 & 10806.61 & 0.05 & 0.44 & 574.00 & 0 \\
c52_6.txt & 11347.50 & 10292.89 & 0.09 & 0.44 & 565.00 & 0 \\
c52_7.txt & 10397.00 & 9968.78 & 0.04 & 0.44 & 585.00 & 0 \\
c52_8.txt & 10757.50 & 10009.12 & 0.07 & 0.44 & 564.00 & 0 \\
c52_9.txt & 11721.40 & 11087.24 & 0.05 & 0.44 & 586.00 & 0 \\
c52_10.txt & 11837.20 & 10890.33 & 0.08 & 0.44 & 564.00 & 0 \\
c52_11.txt & 11268.80 & 10718.30 & 0.05 & 0.44 & 595.00 & 0 \\
c52_12.txt & 11745.40 & 10704.70 & 0.09 & 0.44 & 564.00 & 0 \\
c52_13.txt & 18510.60 & 17749.16 & 0.04 & 0.44 & 605.00 & 0 \\
c52_14.txt & 15226.00 & 13670.36 & 0.10 & 0.44 & 561.00 & 0 \\
c52_15.txt & 17729.20 & 16438.12 & 0.07 & 0.44 & 574.00 & 0 \\
c52_16.txt & 16072.00 & 15023.68 & 0.07 & 0.44 & 562.00 & 0 \\
c52_17.txt & 19357.00 & 18398.02 & 0.05 & 0.44 & 576.00 & 0 \\
c52_18.txt & 16491.50 & 14911.00 & 0.10 & 0.44 & 556.00 & 0 \\
c52_19.txt & 18014.00 & 16945.47 & 0.06 & 0.44 & 588.00 & 0 \\
c52_20.txt & 18758.00 & 17350.81 & 0.08 & 0.44 & 556.00 & 0 \\
c52_21.txt & 20251.60 & 19187.47 & 0.05 & 0.44 & 582.00 & 0 \\
c52_22.txt & 18020.80 & 16017.22 & 0.11 & 0.44 & 570.00 & 0 \\
c52_23.txt & 17797.60 & 16753.39 & 0.06 & 0.44 & 602.00 & 0 \\
c52_24.txt & 17075.00 & 15774.81 & 0.08 & 0.44 & 571.00 & 0 \\
c52_25.txt & 52170.00 & 49301.47 & 0.05 & 0.44 & 566.00 & 0 \\
c52_26.txt & 45410.40 & 42272.34 & 0.07 & 0.44 & 560.00 & 0 \\
c52_27.txt & 48392.20 & 46641.20 & 0.04 & 0.44 & 554.00 & 0 \\
c52_28.txt & 43194.80 & 40827.96 & 0.05 & 0.44 & 569.00 & 0 \\
c52_29.txt & 51580.28 & 48941.55 & 0.05 & 0.44 & 578.00 & 0 \\
c52_30.txt & 46435.50 & 43223.33 & 0.07 & 0.44 & 556.00 & 0 \\
c52_31.txt & 62917.50 & 60037.41 & 0.05 & 0.44 & 585.00 & 0 \\
c52_32.txt & 42728.00 & 39590.54 & 0.07 & 0.44 & 565.00 & 0 \\
c52_33.txt & 53454.40 & 50836.37 & 0.05 & 0.44 & 578.00 & 0 \\
c52_34.txt & 44952.40 & 41702.56 & 0.07 & 0.44 & 568.00 & 0 \\
c52_35.txt & 57464.00 & 55878.33 & 0.03 & 0.44 & 621.00 & 0 \\
c52_36.txt & 41331.20 & 39016.65 & 0.06 & 0.44 & 587.00 & 0 \\
c52_37.txt & 14023.40 & 13369.79 & 0.05 & 0.44 & 630.00 & 0 \\
c52_38.txt & 15785.60 & 14739.17 & 0.07 & 0.44 & 560.00 & 0 \\
c52_39.txt & 12727.00 & 12279.19 & 0.04 & 0.44 & 611.00 & 0 \\
c52_40.txt & 14165.20 & 13283.83 & 0.06 & 0.44 & 570.00 & 0 \\
c52_41.txt & 13755.50 & 12745.10 & 0.07 & 0.44 & 579.00 & 0 \\
c52_42.txt & 16703.00 & 15337.16 & 0.08 & 0.44 & 564.00 & 0 \\
c52_43.txt & 14486.50 & 13629.76 & 0.06 & 0.44 & 593.00 & 0 \\
c52_44.txt & 16146.00 & 15032.91 & 0.07 & 0.44 & 578.00 & 0 \\
c52_45.txt & 14824.40 & 13952.51 & 0.06 & 0.44 & 566.00 & 0 \\
c52_46.txt & 17590.60 & 16401.39 & 0.07 & 0.44 & 587.00 & 0 \\
c52_47.txt & 15019.20 & 14590.62 & 0.03 & 0.44 & 609.00 & 0 \\
c52_48.txt & 17529.00 & 16701.22 & 0.05 & 0.44 & 582.00 & 0 \\
c52_49.txt & 20971.20 & 18879.34 & 0.10 & 0.44 & 552.00 & 0 \\
c52_50.txt & 22557.80 & 20887.39 & 0.07 & 0.44 & 561.00 & 0 \\
c52_51.txt & 23374.60 & 22200.93 & 0.05 & 0.44 & 597.00 & 0 \\
c52_52.txt & 22294.60 & 20613.50 & 0.08 & 0.44 & 557.00 & 0 \\
c52_53.txt & 21526.50 & 19307.23 & 0.10 & 0.44 & 539.00 & 0 \\
c52_54.txt & 22643.00 & 21116.07 & 0.07 & 0.44 & 557.00 & 0 \\
c52_55.txt & 20639.00 & 19397.12 & 0.06 & 0.44 & 577.00 & 0 \\
c52_56.txt & 21983.50 & 19797.88 & 0.10 & 0.44 & 554.00 & 0 \\
c52_57.txt & 24992.60 & 23125.32 & 0.07 & 0.44 & 589.00 & 0 \\
c52_58.txt & 25020.00 & 22597.33 & 0.10 & 0.44 & 554.00 & 0 \\
c52_59.txt & 22499.80 & 21237.59 & 0.06 & 0.44 & 597.00 & 0 \\
c52_60.txt & 23721.00 & 21554.85 & 0.09 & 0.44 & 556.00 & 0 \\
c52_61.txt & 57343.00 & 54918.59 & 0.04 & 0.44 & 552.00 & 0 \\
c52_62.txt & 46550.80 & 43649.62 & 0.06 & 0.44 & 558.00 & 0 \\
c52_63.txt & 51097.20 & 48676.00 & 0.05 & 0.44 & 561.00 & 0 \\
c52_64.txt & 50845.20 & 49227.00 & 0.03 & 0.44 & 569.00 & 0 \\
c52_65.txt & 63548.50 & 61367.23 & 0.03 & 0.44 & 589.00 & 0 \\
c52_66.txt & 50779.00 & 46350.70 & 0.09 & 0.44 & 502.00 & 0 \\
c52_67.txt & 58652.00 & 56222.01 & 0.04 & 0.44 & 599.00 & 0 \\
c52_68.txt & 49355.50 & 45318.07 & 0.08 & 0.44 & 563.00 & 0 \\
c52_69.txt & 60312.00 & 56898.43 & 0.06 & 0.44 & 560.00 & 0 \\
c52_70.txt & 49856.40 & 45529.64 & 0.09 & 0.44 & 563.00 & 0 \\
c52_71.txt & 63429.80 & 60146.11 & 0.05 & 0.44 & 599.00 & 0 \\
c52_72.txt & 49497.00 & 46698.72 & 0.06 & 0.44 & 556.00 & 0 \\
c52_73.txt & 16923.60 & 16923.60 & 0.00 & 0.10 & 192.00 & 1 \\
c52_74.txt & 22493.80 & 22493.80 & 0.00 & 0.07 & 68.00 & 1 \\
c52_75.txt & 17905.80 & 17905.80 & 0.00 & 0.03 & 10.00 & 1 \\
c52_76.txt & 22717.80 & 22717.80 & 0.00 & 0.04 & 1.00 & 1 \\
c52_77.txt & 24063.50 & 23773.36 & 0.01 & 0.44 & 725.00 & 0 \\
c52_78.txt & 34161.50 & 33741.25 & 0.01 & 0.44 & 776.00 & 0 \\
c52_79.txt & 23372.50 & 23098.68 & 0.01 & 0.44 & 795.00 & 0 \\
c52_80.txt & 37513.00 & 37062.80 & 0.01 & 0.44 & 783.00 & 0 \\
c52_81.txt & 25011.80 & 24273.37 & 0.03 & 0.44 & 693.00 & 0 \\
c52_82.txt & 42284.60 & 41019.23 & 0.03 & 0.44 & 636.00 & 0 \\
c52_83.txt & 30021.40 & 29509.79 & 0.02 & 0.44 & 719.00 & 0 \\
c52_84.txt & 38253.40 & 36774.84 & 0.04 & 0.44 & 629.00 & 0 \\
c52_85.txt & 28273.40 & 28042.37 & 0.01 & 0.44 & 969.00 & 0 \\
c52_86.txt & 33928.80 & 33750.82 & 0.01 & 0.44 & 971.00 & 0 \\
c52_87.txt & 27593.80 & 27429.30 & 0.01 & 0.44 & 1091.00 & 0 \\
c52_88.txt & 34623.00 & 34623.00 & 0.00 & 0.16 & 368.00 & 1 \\
c52_89.txt & 34412.50 & 33317.26 & 0.03 & 0.44 & 650.00 & 0 \\
c52_90.txt & 42968.00 & 41905.33 & 0.02 & 0.44 & 618.00 & 0 \\
c52_91.txt & 33227.00 & 32814.43 & 0.01 & 0.44 & 657.00 & 0 \\
c52_92.txt & 39111.00 & 38051.84 & 0.03 & 0.44 & 609.00 & 0 \\
c52_93.txt & 39894.20 & 38793.49 & 0.03 & 0.44 & 617.00 & 0 \\
c52_94.txt & 45737.00 & 43743.23 & 0.04 & 0.44 & 595.00 & 0 \\
c52_95.txt & 36475.60 & 35078.25 & 0.04 & 0.44 & 618.00 & 0 \\
c52_96.txt & 49859.80 & 48575.13 & 0.03 & 0.44 & 604.00 & 0 \\
c52_97.txt & 68682.60 & 65354.84 & 0.05 & 0.44 & 575.00 & 0 \\
c52_98.txt & 84066.60 & 82079.48 & 0.02 & 0.44 & 588.00 & 0 \\
c52_99.txt & 75697.60 & 73184.46 & 0.03 & 0.44 & 608.00 & 0 \\
c52_100.txt & 67904.80 & 65433.47 & 0.04 & 0.44 & 571.00 & 0 \\
c52_101.txt & 75074.50 & 70855.80 & 0.06 & 0.44 & 571.00 & 0 \\
c52_102.txt & 83845.00 & 79885.76 & 0.05 & 0.44 & 576.00 & 0 \\
c52_103.txt & 73609.50 & 70441.11 & 0.04 & 0.44 & 600.00 & 0 \\
c52_104.txt & 74643.50 & 71316.81 & 0.04 & 0.44 & 574.00 & 0 \\
c52_105.txt & 72160.40 & 68995.19 & 0.04 & 0.44 & 567.00 & 0 \\
c52_106.txt & 84605.40 & 81276.05 & 0.04 & 0.44 & 580.00 & 0 \\
c52_107.txt & 66024.00 & 62038.47 & 0.06 & 0.44 & 575.00 & 0 \\
c52_108.txt & 69579.60 & 65015.97 & 0.07 & 0.44 & 555.00 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [11]:
table_resume = pd.DataFrame()
table_resume['dif1'] = table_math['fop'] - table_first_feasible['objval0']
table_resume['dif2'] = table_math['fop'] - table_feasible_tmean['objval2']
table_resume['dif3'] = table_math['fop'] - table_feasible_tmax['objval1']
table_resume

        dif1    dif2    dif3
0    -2990.8  -164.2  -164.2
1    -2621.2  -245.2  -245.2
2    -3958.4   -92.2   -92.2
3    -3705.8  -126.4  -126.4
4    -2815.5  -280.5  -280.5
..       ...     ...     ...
103 -41630.5  2710.5  2710.5
104 -55309.4  1541.4  1939.8
105 -32942.2  1432.4  1432.4
106 -64970.4 -2024.0 -2024.0
107 -52424.4 -2852.0 -2852.0

[108 rows x 3 columns]

In [12]:
positive_count_dif1 = (table_resume['dif1'] < 0).sum()
positive_count_dif2 = (table_resume['dif2'] < 0).sum()
positive_count_dif3 = (table_resume['dif3'] < 0).sum()
print(f"Ganho do math em relacao ao mip first feasible: {positive_count_dif1}")
print(f"Ganho do math em relacao ao mip first feasible tmean: {positive_count_dif2}")
print(f"Ganho do math em relacao ao mip first feasible tmax: {positive_count_dif3}")

Ganho do math em relacao ao mip first feasible: 108
Ganho do math em relacao ao mip first feasible tmean: 77
Ganho do math em relacao ao mip first feasible tmax: 75

In [13]:
def tabela_mip(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','objval','bound','gap','time','nodes','opt']
    table = table[['instance','bound','objval','gap','time','nodes','opt']]

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'c52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'c52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'bound':tab['bound'].mean().round(2),
            'objval':tab['objval'].mean().round(2),
            'gap':tab['gap'].mean().round(2),
            'time':tab['time'].mean().round(2),
            'nodes':tab['nodes'].mean().round(2),
            'opt':tab['opt'].sum().round(2),
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [14]:
def tabela_math(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','rf','time_rf','fop','time_fop']
    table['time_total'] = table['time_rf']+table['time_fop']

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'c52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'c52_{i}.txt'].index,'grupo'] = set_
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'rf':tab['rf'].mean(),
            'time_rf':tab['time_rf'].mean(),
            'fop':tab['fop'].mean(),
            'time_fop':tab['time_fop'].mean(),
            'time_total':tab['time_total'].mean()
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [15]:
file=f"std_mip/result/clsr_std_mip_first_feasible.txt"

table_first_feasible_set, table_first_feasible_set_ = tabela_mip(file)

table_first_feasible_set = table_first_feasible_set[['instance','objval','time']]
table_first_feasible

        instance   objval0  time0
0      c52_1.txt   12770.8    0.0
1      c52_2.txt   12827.8    0.0
2      c52_3.txt   13398.0    0.0
3      c52_4.txt   14070.0    0.0
4      c52_5.txt   13936.5    0.0
..           ...       ...    ...
103  c52_104.txt  118984.5    0.0
104  c52_105.txt  129011.2    0.0
105  c52_106.txt  118980.0    0.0
106  c52_107.txt  128970.4    0.0
107  c52_108.txt  119152.0    0.0

[108 rows x 3 columns]

In [16]:
latex_table_first_feasible_set = table_first_feasible_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Primeira solução viável encontrada pelo solver",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_primeira_sol_viavel_solver_set",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_first_feasible_set)

\begin{table}[htbp]
\caption{Primeira solução viável encontrada pelo solver}
\label{tab:clsr_primeira_sol_viavel_solver_set}
\begin{tabular}{lrr}
\toprule
instance & objval & time \\
\midrule
set01 & 14809.66 & 0.00 \\
set02 & 26279.88 & 0.00 \\
set03 & 80850.77 & 0.00 \\
set04 & 22286.62 & 0.00 \\
set05 & 32880.77 & 0.00 \\
set06 & 88062.52 & 0.00 \\
set07 & 58982.24 & 0.00 \\
set08 & 69102.01 & 0.00 \\
set09 & 122652.12 & 0.00 \\
\bottomrule
\end{tabular}
\end{table}

In [17]:
file=f"std_mip/result/clsr_std_mip_tmax.txt"

table_feasible_tmax_set, table_feasible_tmax_set_ = tabela_mip(file)

In [18]:
latex_table_feasible_tmax_set = table_feasible_tmax_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMAX segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_melhor_sol_viavel_tmean_set",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmax_set)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMAX segundos}
\label{tab:clsr_melhor_sol_viavel_tmean_set}
\begin{tabular}{lrrrrrr}
\toprule
instance & bound & objval & gap & time & nodes & opt \\
\midrule
set01 & 10245.66 & 10900.56 & 0.06 & 0.72 & 600.17 & 0 \\
set02 & 16577.26 & 17748.74 & 0.07 & 0.72 & 617.83 & 0 \\
set03 & 46618.20 & 49169.14 & 0.05 & 0.72 & 603.08 & 0 \\
set04 & 14426.08 & 15220.58 & 0.05 & 0.72 & 618.42 & 0 \\
set05 & 20972.73 & 22682.55 & 0.08 & 0.72 & 595.67 & 0 \\
set06 & 51388.44 & 54199.51 & 0.05 & 0.72 & 602.00 & 0 \\
set07 & 27497.89 & 27822.47 & 0.01 & 0.50 & 682.92 & 4 \\
set08 & 36398.87 & 37164.76 & 0.02 & 0.63 & 884.92 & 4 \\
set09 & 71442.55 & 74569.47 & 0.04 & 0.72 & 615.33 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [19]:
file=f"std_mip/result/clsr_std_mip_tmean.txt"

table_feasible_tmean_set, table_feasible_tmean_set_ = tabela_mip(file)

In [20]:
latex_table_feasible_tmean_set = table_feasible_tmean_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo solver em TMEAN segundos",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_melhor_sol_viavel_tmean_set",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_feasible_tmean_set)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo solver em TMEAN segundos}
\label{tab:clsr_melhor_sol_viavel_tmean_set}
\begin{tabular}{lrrrrrr}
\toprule
instance & bound & objval & gap & time & nodes & opt \\
\midrule
set01 & 10180.63 & 10907.89 & 0.07 & 0.44 & 572.50 & 0 \\
set02 & 16518.29 & 17775.27 & 0.07 & 0.44 & 575.25 & 0 \\
set03 & 46522.48 & 49169.22 & 0.06 & 0.44 & 573.92 & 0 \\
set04 & 14338.55 & 15229.62 & 0.06 & 0.44 & 585.75 & 0 \\
set05 & 20892.88 & 22685.30 & 0.08 & 0.44 & 565.83 & 0 \\
set06 & 51250.18 & 54272.20 & 0.06 & 0.44 & 564.25 & 0 \\
set07 & 27441.19 & 27893.56 & 0.01 & 0.31 & 502.25 & 4 \\
set08 & 36343.70 & 37175.34 & 0.02 & 0.42 & 697.25 & 1 \\
set09 & 71323.12 & 74657.79 & 0.05 & 0.44 & 578.33 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [21]:
table_feasible_tmax_set

  instance     bound    objval   gap  time   nodes  opt
0    set01  10245.66  10900.56  0.06  0.72  600.17    0
1    set02  16577.26  17748.74  0.07  0.72  617.83    0
2    set03  46618.20  49169.14  0.05  0.72  603.08    0
3    set04  14426.08  15220.58  0.05  0.72  618.42    0
4    set05  20972.73  22682.55  0.08  0.72  595.67    0
5    set06  51388.44  54199.51  0.05  0.72  602.00    0
6    set07  27497.89  27822.47  0.01  0.50  682.92    4
7    set08  36398.87  37164.76  0.02  0.63  884.92    4
8    set09  71442.55  74569.47  0.04  0.72  615.33    0

In [22]:
table_feasible_tmean_set

  instance     bound    objval   gap  time   nodes  opt
0    set01  10180.63  10907.89  0.07  0.44  572.50    0
1    set02  16518.29  17775.27  0.07  0.44  575.25    0
2    set03  46522.48  49169.22  0.06  0.44  573.92    0
3    set04  14338.55  15229.62  0.06  0.44  585.75    0
4    set05  20892.88  22685.30  0.08  0.44  565.83    0
5    set06  51250.18  54272.20  0.06  0.44  564.25    0
6    set07  27441.19  27893.56  0.01  0.31  502.25    4
7    set08  36343.70  37175.34  0.02  0.42  697.25    1
8    set09  71323.12  74657.79  0.05  0.44  578.33    0

In [23]:
file=f"std_math/result/clsr_std_math.txt"

table_math_set, table_math_set_ = tabela_math(file)

In [24]:
latex_table_math_set = table_math_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Melhor solução viável encontrada pelo RF+FOP",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_sol_viavel_math_set",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_math_set)

\begin{table}[htbp]
\caption{Melhor solução viável encontrada pelo RF+FOP}
\label{tab:clsr_sol_viavel_math_set}
\begin{tabular}{lrrrrrr}
\toprule
instance & rf & time_rf & fop & time_fop & time_total \\
\midrule
set01 & 10750.78 & 0.36 & 10695.61 & 0.25 & 0.61 \\
set02 & 17400.32 & 0.32 & 17340.15 & 0.24 & 0.57 \\
set03 & 48494.73 & 0.32 & 48315.78 & 0.23 & 0.56 \\
set04 & 15619.61 & 0.25 & 15010.42 & 0.20 & 0.45 \\
set05 & 22638.51 & 0.26 & 22237.27 & 0.18 & 0.45 \\
set06 & 53523.82 & 0.24 & 53164.47 & 0.19 & 0.43 \\
set07 & 32192.93 & 0.15 & 27965.20 & 0.14 & 0.29 \\
set08 & 41803.39 & 0.16 & 37162.18 & 0.13 & 0.28 \\
set09 & 79636.47 & 0.17 & 76799.63 & 0.13 & 0.29 \\
\bottomrule
\end{tabular}
\end{table}

In [25]:
table_math_set

  instance            rf   time_rf           fop  time_fop  time_total
0    set01  10750.783333  0.355833  10695.608333  0.251667    0.607500
1    set02  17400.316667  0.325000  17340.150000  0.244167    0.569167
2    set03  48494.733333  0.324167  48315.783333  0.234167    0.558333
3    set04  15619.608333  0.252500  15010.425000  0.200000    0.452500
4    set05  22638.508333  0.264167  22237.266667  0.184167    0.448333
5    set06  53523.816667  0.239167  53164.475000  0.194167    0.433333
6    set07  32192.933333  0.152500  27965.200000  0.140833    0.293333
7    set08  41803.391667  0.155833  37162.175000  0.125833    0.281667
8    set09  79636.475000  0.167500  76799.633333  0.125833    0.293333

In [26]:
file=f"std_mip/result/clsr_std_mip.txt"

table_mip_set, table_mip_set_ = tabela_mip(file)
table_mip_set

  instance     bound    objval  gap     time       nodes  opt
0    set01  10636.11  10641.49  0.0   990.13  1442878.42   11
1    set02  17190.73  17222.92  0.0  1831.62  2060173.67    9
2    set03  48099.39  48173.38  0.0  2456.42  2593639.17    6
3    set04  14875.52  14875.52  0.0   155.64   214424.08   12
4    set05  21784.58  21815.98  0.0  1598.68  1656838.33    9
5    set06  52746.64  52787.82  0.0  1944.77  1901926.92    9
6    set07  27721.94  27721.94  0.0     2.25     4031.67   12
7    set08  36906.26  36906.27  0.0    13.91    21119.75   12
8    set09  72747.59  72865.03  0.0  1414.60  1913768.83    9

In [27]:
latex_table_mip_set = table_mip_set.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    caption="Resultados do MIP",  # The caption to appear above the table in the LaTeX document
    label="tab:clsr_sol_mip",  # A label used for referencing the table within the LaTeX document
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="lrrrrrr",  # The format of the columns: left-aligend first column and center-aligned remaining columns as per APA guidelines
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

print(latex_table_mip_set)

\begin{table}[htbp]
\caption{Resultados do MIP}
\label{tab:clsr_sol_mip}
\begin{tabular}{lrrrrrr}
\toprule
instance & bound & objval & gap & time & nodes & opt \\
\midrule
set01 & 10636.11 & 10641.49 & 0.00 & 990.13 & 1442878.42 & 11 \\
set02 & 17190.73 & 17222.92 & 0.00 & 1831.62 & 2060173.67 & 9 \\
set03 & 48099.39 & 48173.38 & 0.00 & 2456.42 & 2593639.17 & 6 \\
set04 & 14875.52 & 14875.52 & 0.00 & 155.64 & 214424.08 & 12 \\
set05 & 21784.58 & 21815.98 & 0.00 & 1598.68 & 1656838.33 & 9 \\
set06 & 52746.64 & 52787.82 & 0.00 & 1944.77 & 1901926.92 & 9 \\
set07 & 27721.94 & 27721.94 & 0.00 & 2.25 & 4031.67 & 12 \\
set08 & 36906.26 & 36906.27 & 0.00 & 13.91 & 21119.75 & 12 \\
set09 & 72747.59 & 72865.03 & 0.00 & 1414.60 & 1913768.83 & 9 \\
\bottomrule
\end{tabular}
\end{table}

In [28]:
file=f"std_mip/result/clsr_std_mip.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

tab = pd.DataFrame()
tab = pd.concat([tab, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

tab_mip = tab
tab_mip

        instance     bound    objval  gap     time       nodes  opt
0      c52_1.txt   9746.20   9746.19  0.0   199.58   280754.00    1
1      c52_2.txt  10120.20  10120.19  0.0  2156.82  2339911.00    1
2      c52_3.txt   9334.00   9333.99  0.0    50.00    72555.00    1
3      c52_4.txt  10332.00  10331.99  0.0   430.70   590795.00    1
4      c52_5.txt  11111.50  11111.50  0.0    73.16   108672.00    1
..           ...       ...       ...  ...      ...         ...  ...
104  c52_105.txt  70650.60  70650.55  0.0   132.33   168304.00    1
105  c52_106.txt  83134.40  82915.84  0.0  3600.00  3995895.00    0
106  c52_107.txt  63700.80  63700.80  0.0   108.50   137120.00    1
107  c52_108.txt  66727.60  66727.60  0.0    87.28   120460.00    1
108       resume  33667.82  33634.31  0.0  1156.45  1312088.98   89

[109 rows x 7 columns]

In [29]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set01"]
)

set01_mip = tab
#set01_mip

In [30]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set02"]
)

set02_mip = tab
#set02_mip

In [31]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set03"]
)

set03_mip = tab
#set03_mip

In [32]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set04"]
)

set04_mip = tab
#set04_mip

In [33]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set05"]
)

set05_mip = tab
#set05_mip

In [34]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set06"]
)

set06_mip = tab
#set06_mip

In [35]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set07"]
)

set07_mip = tab
#set07_mip

In [36]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set08"]
)

set08_mip = tab
#set08_mip

In [37]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,109):
    t = tab_mip.loc[tab_mip['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean().round(2),
    'objval':tab['objval'].mean().round(2),
    'gap':tab['gap'].mean().round(2),
    'time':tab['time'].mean().round(2),
    'nodes':tab['nodes'].mean().round(2),
    'opt':tab['opt'].sum().round(2),
    },index=["set09"]
)

set09_mip = tab
#set09_mip

In [38]:
res_mip = pd.DataFrame()
res_mip = pd.concat([res_mip,set01_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set02_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set03_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set04_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set05_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set06_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set07_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set08_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set09_mip], ignore_index= True)
res_mip

        instance    bound    objval  gap     time      nodes  opt
0      c52_1.txt   9746.2   9746.19  0.0   199.58   280754.0    1
1      c52_2.txt  10120.2  10120.19  0.0  2156.82  2339911.0    1
2      c52_3.txt   9334.0   9333.99  0.0    50.00    72555.0    1
3      c52_4.txt  10332.0  10331.99  0.0   430.70   590795.0    1
4      c52_5.txt  11111.5  11111.50  0.0    73.16   108672.0    1
..           ...      ...       ...  ...      ...        ...  ...
103  c52_104.txt  72897.5  72897.43  0.0   866.63  1240314.0    1
104  c52_105.txt  70650.6  70650.55  0.0   132.33   168304.0    1
105  c52_106.txt  83134.4  82915.84  0.0  3600.00  3995895.0    0
106  c52_107.txt  63700.8  63700.80  0.0   108.50   137120.0    1
107  c52_108.txt  66727.6  66727.60  0.0    87.28   120460.0    1

[108 rows x 7 columns]

In [41]:
tab = pd.DataFrame({
    'instance':f'res_mip',
    'bound':res_mip['bound'].mean().round(2),
    'objval':res_mip['objval'].mean().round(2),
    'gap':res_mip['gap'].mean().round(2),
    'time':res_mip['time'].mean().round(2),
    'nodes':res_mip['nodes'].mean().round(2),
    'opt':res_mip['opt'].sum().round(2),
    },index=[f'res_mip']
)

res_mip = pd.concat([res_mip, tab], ignore_index=True)
#res_mip

print(res_mip[['instance','objval','bound','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrrr}
\toprule
instance & objval & bound & gap & time & nodes & opt \\
\midrule
c52_1.txt & 9746.19 & 9746.20 & 0.00 & 199.58 & 280754.00 & 1 \\
c52_2.txt & 10120.19 & 10120.20 & 0.00 & 2156.82 & 2339911.00 & 1 \\
c52_3.txt & 9333.99 & 9334.00 & 0.00 & 50.00 & 72555.00 & 1 \\
c52_4.txt & 10331.99 & 10332.00 & 0.00 & 430.70 & 590795.00 & 1 \\
c52_5.txt & 11111.50 & 11111.50 & 0.00 & 73.16 & 108672.00 & 1 \\
c52_6.txt & 10937.97 & 11002.50 & 0.01 & 3600.00 & 5451717.00 & 0 \\
c52_7.txt & 10249.50 & 10249.50 & 0.00 & 68.98 & 113180.00 & 1 \\
c52_8.txt & 10509.99 & 10510.00 & 0.00 & 493.51 & 659225.00 & 1 \\
c52_9.txt & 11470.79 & 11470.80 & 0.00 & 369.82 & 524935.00 & 1 \\
c52_10.txt & 11561.39 & 11561.40 & 0.00 & 2964.85 & 4825402.00 & 1 \\
c52_11.txt & 11010.60 & 11010.60 & 0.00 & 38.59 & 63399.00 & 1 \\
c52_12.txt & 11249.19 & 11249.20 & 0.00 & 1435.59 & 2283996.00 & 1 \\
c52_13.txt & 18284.78 & 18284.80 & 0.00 & 1038.85 & 1088134.00 & 1 \\
c52_14.txt & 14390.19 & 14390.20 & 0.00 & 2353.23 & 2014351.00 & 1 \\
c52_15.txt & 16924.39 & 16924.40 & 0.00 & 343.33 & 400717.00 & 1 \\
c52_16.txt & 15685.36 & 15733.00 & 0.00 & 3600.00 & 3100372.00 & 0 \\
c52_17.txt & 18980.98 & 18981.00 & 0.00 & 1571.86 & 1942517.00 & 1 \\
c52_18.txt & 15817.82 & 15919.00 & 0.01 & 3600.00 & 4164397.00 & 0 \\
c52_19.txt & 17503.48 & 17503.50 & 0.00 & 454.97 & 448145.00 & 1 \\
c52_20.txt & 18055.98 & 18056.00 & 0.00 & 2160.97 & 2107254.00 & 1 \\
c52_21.txt & 19802.98 & 19803.00 & 0.00 & 1303.39 & 1859615.00 & 1 \\
c52_22.txt & 16837.48 & 17074.80 & 0.01 & 3600.00 & 5241350.00 & 0 \\
c52_23.txt & 17395.59 & 17395.60 & 0.00 & 180.74 & 294500.00 & 1 \\
c52_24.txt & 16609.78 & 16609.80 & 0.00 & 1772.04 & 2060732.00 & 1 \\
c52_25.txt & 51311.61 & 51449.20 & 0.00 & 3600.00 & 3231869.00 & 0 \\
c52_26.txt & 44314.65 & 44427.40 & 0.00 & 3600.00 & 3954350.00 & 0 \\
c52_27.txt & 47568.95 & 47569.00 & 0.00 & 2241.88 & 2497884.00 & 1 \\
c52_28.txt & 42280.84 & 42479.60 & 0.00 & 3600.00 & 3744352.00 & 0 \\
c52_29.txt & 50492.45 & 50492.50 & 0.00 & 3350.71 & 3203004.00 & 1 \\
c52_30.txt & 45154.54 & 45420.00 & 0.01 & 3600.00 & 3958033.00 & 0 \\
c52_31.txt & 61678.62 & 61766.50 & 0.00 & 3600.00 & 3636338.00 & 0 \\
c52_32.txt & 41341.46 & 41341.50 & 0.00 & 381.92 & 476358.00 & 1 \\
c52_33.txt & 52817.51 & 52902.60 & 0.00 & 3600.00 & 3582037.00 & 0 \\
c52_34.txt & 42954.96 & 42955.00 & 0.00 & 442.54 & 720897.00 & 1 \\
c52_35.txt & 56869.74 & 56869.80 & 0.00 & 839.46 & 1150619.00 & 1 \\
c52_36.txt & 40407.36 & 40407.40 & 0.00 & 620.49 & 967929.00 & 1 \\
c52_37.txt & 13734.60 & 13734.60 & 0.00 & 39.94 & 61163.00 & 1 \\
c52_38.txt & 15433.39 & 15433.40 & 0.00 & 1163.66 & 1680117.00 & 1 \\
c52_39.txt & 12592.60 & 12592.60 & 0.00 & 18.78 & 29610.00 & 1 \\
c52_40.txt & 13798.40 & 13798.40 & 0.00 & 58.27 & 76844.00 & 1 \\
c52_41.txt & 13337.00 & 13337.00 & 0.00 & 97.52 & 116822.00 & 1 \\
c52_42.txt & 16130.50 & 16130.50 & 0.00 & 307.36 & 378731.00 & 1 \\
c52_43.txt & 13936.00 & 13936.00 & 0.00 & 14.24 & 18493.00 & 1 \\
c52_44.txt & 15675.00 & 15675.00 & 0.00 & 42.32 & 53572.00 & 1 \\
c52_45.txt & 14560.20 & 14560.20 & 0.00 & 30.69 & 37089.00 & 1 \\
c52_46.txt & 17211.40 & 17211.40 & 0.00 & 55.80 & 79795.00 & 1 \\
c52_47.txt & 14815.80 & 14815.80 & 0.00 & 4.67 & 6254.00 & 1 \\
c52_48.txt & 17281.40 & 17281.40 & 0.00 & 34.47 & 34599.00 & 1 \\
c52_49.txt & 19933.58 & 19933.60 & 0.00 & 2515.42 & 2833353.00 & 1 \\
c52_50.txt & 21749.02 & 21818.60 & 0.00 & 3600.00 & 3571096.00 & 0 \\
c52_51.txt & 22844.19 & 22844.20 & 0.00 & 234.34 & 372299.00 & 1 \\
c52_52.txt & 21348.38 & 21348.40 & 0.00 & 2212.29 & 2105230.00 & 1 \\
c52_53.txt & 20285.98 & 20286.00 & 0.00 & 541.81 & 692124.00 & 1 \\
c52_54.txt & 22161.49 & 22161.50 & 0.00 & 1259.05 & 1305733.00 & 1 \\
c52_55.txt & 20122.49 & 20122.50 & 0.00 & 328.44 & 334541.00 & 1 \\
c52_56.txt & 20805.45 & 20903.00 & 0.00 & 3600.00 & 3606735.00 & 0 \\
c52_57.txt & 23839.38 & 23839.40 & 0.00 & 241.80 & 306059.00 & 1 \\
c52_58.txt & 23725.28 & 23934.80 & 0.01 & 3600.00 & 3575694.00 & 0 \\
c52_59.txt & 22049.98 & 22050.00 & 0.00 & 627.77 & 754831.00 & 1 \\
c52_60.txt & 22549.78 & 22549.80 & 0.00 & 423.22 & 424365.00 & 1 \\
c52_61.txt & 56409.55 & 56409.60 & 0.00 & 1838.68 & 1678779.00 & 1 \\
c52_62.txt & 45029.14 & 45254.40 & 0.00 & 3600.00 & 3364009.00 & 0 \\
c52_63.txt & 50527.95 & 50528.00 & 0.00 & 1748.00 & 1980934.00 & 1 \\
c52_64.txt & 50061.73 & 50240.20 & 0.00 & 3600.00 & 4415920.00 & 0 \\
c52_65.txt & 62262.94 & 62263.00 & 0.00 & 596.82 & 705113.00 & 1 \\
c52_66.txt & 48396.46 & 48396.50 & 0.00 & 891.94 & 780726.00 & 1 \\
c52_67.txt & 57858.94 & 57859.00 & 0.00 & 1158.98 & 1052420.00 & 1 \\
c52_68.txt & 46833.96 & 46834.00 & 0.00 & 1934.86 & 1776898.00 & 1 \\
c52_69.txt & 58657.34 & 58657.40 & 0.00 & 2391.84 & 1883456.00 & 1 \\
c52_70.txt & 47489.17 & 47579.20 & 0.00 & 3600.00 & 2668618.00 & 0 \\
c52_71.txt & 61125.14 & 61125.20 & 0.00 & 448.57 & 488910.00 & 1 \\
c52_72.txt & 48307.35 & 48307.40 & 0.00 & 1527.52 & 2027340.00 & 1 \\
c52_73.txt & 16923.60 & 16923.60 & 0.00 & 0.10 & 192.00 & 1 \\
c52_74.txt & 22493.80 & 22493.80 & 0.00 & 0.07 & 68.00 & 1 \\
c52_75.txt & 17905.80 & 17905.80 & 0.00 & 0.04 & 10.00 & 1 \\
c52_76.txt & 22717.80 & 22717.80 & 0.00 & 0.04 & 1.00 & 1 \\
c52_77.txt & 23991.00 & 23991.00 & 0.00 & 0.76 & 1067.00 & 1 \\
c52_78.txt & 34086.00 & 34086.00 & 0.00 & 1.39 & 2702.00 & 1 \\
c52_79.txt & 23348.50 & 23348.50 & 0.00 & 0.83 & 1487.00 & 1 \\
c52_80.txt & 37338.00 & 37338.00 & 0.00 & 1.00 & 2059.00 & 1 \\
c52_81.txt & 24822.60 & 24822.60 & 0.00 & 2.26 & 3157.00 & 1 \\
c52_82.txt & 41730.60 & 41730.60 & 0.00 & 10.91 & 19180.00 & 1 \\
c52_83.txt & 29855.00 & 29855.00 & 0.00 & 1.23 & 2885.00 & 1 \\
c52_84.txt & 37450.60 & 37450.60 & 0.00 & 8.34 & 15572.00 & 1 \\
c52_85.txt & 28188.40 & 28188.40 & 0.00 & 0.57 & 1641.00 & 1 \\
c52_86.txt & 33886.80 & 33886.80 & 0.00 & 0.56 & 1476.00 & 1 \\
c52_87.txt & 27593.80 & 27593.80 & 0.00 & 0.54 & 1473.00 & 1 \\
c52_88.txt & 34623.00 & 34623.00 & 0.00 & 0.16 & 368.00 & 1 \\
c52_89.txt & 33823.98 & 33824.00 & 0.00 & 5.53 & 12333.00 & 1 \\
c52_90.txt & 42633.00 & 42633.00 & 0.00 & 20.24 & 34533.00 & 1 \\
c52_91.txt & 33227.00 & 33227.00 & 0.00 & 3.08 & 8263.00 & 1 \\
c52_92.txt & 38966.00 & 38966.00 & 0.00 & 22.10 & 28134.00 & 1 \\
c52_93.txt & 39465.00 & 39465.00 & 0.00 & 8.96 & 16486.00 & 1 \\
c52_94.txt & 45048.80 & 45048.80 & 0.00 & 59.45 & 78222.00 & 1 \\
c52_95.txt & 35905.00 & 35905.00 & 0.00 & 12.35 & 22684.00 & 1 \\
c52_96.txt & 49514.40 & 49514.40 & 0.00 & 33.41 & 47824.00 & 1 \\
c52_97.txt & 66347.34 & 66347.40 & 0.00 & 101.40 & 123231.00 & 1 \\
c52_98.txt & 83029.40 & 83465.80 & 0.01 & 3600.00 & 6811192.00 & 0 \\
c52_99.txt & 74427.13 & 74427.20 & 0.00 & 1892.57 & 2212420.00 & 1 \\
c52_100.txt & 66630.94 & 66631.00 & 0.00 & 889.94 & 1015948.00 & 1 \\
c52_101.txt & 72277.21 & 73031.00 & 0.01 & 3600.00 & 4249475.00 & 0 \\
c52_102.txt & 81357.93 & 81358.00 & 0.00 & 1705.38 & 2447235.00 & 1 \\
c52_103.txt & 72008.93 & 72009.00 & 0.00 & 391.12 & 443632.00 & 1 \\
c52_104.txt & 72897.43 & 72897.50 & 0.00 & 866.63 & 1240314.00 & 1 \\
c52_105.txt & 70650.55 & 70650.60 & 0.00 & 132.33 & 168304.00 & 1 \\
c52_106.txt & 82915.84 & 83134.40 & 0.00 & 3600.00 & 3995895.00 & 0 \\
c52_107.txt & 63700.80 & 63700.80 & 0.00 & 108.50 & 137120.00 & 1 \\
c52_108.txt & 66727.60 & 66727.60 & 0.00 & 87.28 & 120460.00 & 1 \\
res_mip & 33634.31 & 33667.82 & 0.00 & 1156.45 & 1312088.98 & 89 \\
res_mip & 33634.31 & 33667.82 & 0.00 & 1156.45 & 1312088.98 & 178 \\
\bottomrule
\end{tabular}

In [40]:
print(res_mip[['instance','objval','bound','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrrr}
\toprule
instance & objval & bound & gap & time & nodes & opt \\
\midrule
c52_1.txt & 9746.19 & 9746.20 & 0.00 & 199.58 & 280754.00 & 1 \\
c52_2.txt & 10120.19 & 10120.20 & 0.00 & 2156.82 & 2339911.00 & 1 \\
c52_3.txt & 9333.99 & 9334.00 & 0.00 & 50.00 & 72555.00 & 1 \\
c52_4.txt & 10331.99 & 10332.00 & 0.00 & 430.70 & 590795.00 & 1 \\
c52_5.txt & 11111.50 & 11111.50 & 0.00 & 73.16 & 108672.00 & 1 \\
c52_6.txt & 10937.97 & 11002.50 & 0.01 & 3600.00 & 5451717.00 & 0 \\
c52_7.txt & 10249.50 & 10249.50 & 0.00 & 68.98 & 113180.00 & 1 \\
c52_8.txt & 10509.99 & 10510.00 & 0.00 & 493.51 & 659225.00 & 1 \\
c52_9.txt & 11470.79 & 11470.80 & 0.00 & 369.82 & 524935.00 & 1 \\
c52_10.txt & 11561.39 & 11561.40 & 0.00 & 2964.85 & 4825402.00 & 1 \\
c52_11.txt & 11010.60 & 11010.60 & 0.00 & 38.59 & 63399.00 & 1 \\
c52_12.txt & 11249.19 & 11249.20 & 0.00 & 1435.59 & 2283996.00 & 1 \\
c52_13.txt & 18284.78 & 18284.80 & 0.00 & 1038.85 & 1088134.00 & 1 \\
c52_14.txt & 14390.19 & 14390.20 & 0.00 & 2353.23 & 2014351.00 & 1 \\
c52_15.txt & 16924.39 & 16924.40 & 0.00 & 343.33 & 400717.00 & 1 \\
c52_16.txt & 15685.36 & 15733.00 & 0.00 & 3600.00 & 3100372.00 & 0 \\
c52_17.txt & 18980.98 & 18981.00 & 0.00 & 1571.86 & 1942517.00 & 1 \\
c52_18.txt & 15817.82 & 15919.00 & 0.01 & 3600.00 & 4164397.00 & 0 \\
c52_19.txt & 17503.48 & 17503.50 & 0.00 & 454.97 & 448145.00 & 1 \\
c52_20.txt & 18055.98 & 18056.00 & 0.00 & 2160.97 & 2107254.00 & 1 \\
c52_21.txt & 19802.98 & 19803.00 & 0.00 & 1303.39 & 1859615.00 & 1 \\
c52_22.txt & 16837.48 & 17074.80 & 0.01 & 3600.00 & 5241350.00 & 0 \\
c52_23.txt & 17395.59 & 17395.60 & 0.00 & 180.74 & 294500.00 & 1 \\
c52_24.txt & 16609.78 & 16609.80 & 0.00 & 1772.04 & 2060732.00 & 1 \\
c52_25.txt & 51311.61 & 51449.20 & 0.00 & 3600.00 & 3231869.00 & 0 \\
c52_26.txt & 44314.65 & 44427.40 & 0.00 & 3600.00 & 3954350.00 & 0 \\
c52_27.txt & 47568.95 & 47569.00 & 0.00 & 2241.88 & 2497884.00 & 1 \\
c52_28.txt & 42280.84 & 42479.60 & 0.00 & 3600.00 & 3744352.00 & 0 \\
c52_29.txt & 50492.45 & 50492.50 & 0.00 & 3350.71 & 3203004.00 & 1 \\
c52_30.txt & 45154.54 & 45420.00 & 0.01 & 3600.00 & 3958033.00 & 0 \\
c52_31.txt & 61678.62 & 61766.50 & 0.00 & 3600.00 & 3636338.00 & 0 \\
c52_32.txt & 41341.46 & 41341.50 & 0.00 & 381.92 & 476358.00 & 1 \\
c52_33.txt & 52817.51 & 52902.60 & 0.00 & 3600.00 & 3582037.00 & 0 \\
c52_34.txt & 42954.96 & 42955.00 & 0.00 & 442.54 & 720897.00 & 1 \\
c52_35.txt & 56869.74 & 56869.80 & 0.00 & 839.46 & 1150619.00 & 1 \\
c52_36.txt & 40407.36 & 40407.40 & 0.00 & 620.49 & 967929.00 & 1 \\
c52_37.txt & 13734.60 & 13734.60 & 0.00 & 39.94 & 61163.00 & 1 \\
c52_38.txt & 15433.39 & 15433.40 & 0.00 & 1163.66 & 1680117.00 & 1 \\
c52_39.txt & 12592.60 & 12592.60 & 0.00 & 18.78 & 29610.00 & 1 \\
c52_40.txt & 13798.40 & 13798.40 & 0.00 & 58.27 & 76844.00 & 1 \\
c52_41.txt & 13337.00 & 13337.00 & 0.00 & 97.52 & 116822.00 & 1 \\
c52_42.txt & 16130.50 & 16130.50 & 0.00 & 307.36 & 378731.00 & 1 \\
c52_43.txt & 13936.00 & 13936.00 & 0.00 & 14.24 & 18493.00 & 1 \\
c52_44.txt & 15675.00 & 15675.00 & 0.00 & 42.32 & 53572.00 & 1 \\
c52_45.txt & 14560.20 & 14560.20 & 0.00 & 30.69 & 37089.00 & 1 \\
c52_46.txt & 17211.40 & 17211.40 & 0.00 & 55.80 & 79795.00 & 1 \\
c52_47.txt & 14815.80 & 14815.80 & 0.00 & 4.67 & 6254.00 & 1 \\
c52_48.txt & 17281.40 & 17281.40 & 0.00 & 34.47 & 34599.00 & 1 \\
c52_49.txt & 19933.58 & 19933.60 & 0.00 & 2515.42 & 2833353.00 & 1 \\
c52_50.txt & 21749.02 & 21818.60 & 0.00 & 3600.00 & 3571096.00 & 0 \\
c52_51.txt & 22844.19 & 22844.20 & 0.00 & 234.34 & 372299.00 & 1 \\
c52_52.txt & 21348.38 & 21348.40 & 0.00 & 2212.29 & 2105230.00 & 1 \\
c52_53.txt & 20285.98 & 20286.00 & 0.00 & 541.81 & 692124.00 & 1 \\
c52_54.txt & 22161.49 & 22161.50 & 0.00 & 1259.05 & 1305733.00 & 1 \\
c52_55.txt & 20122.49 & 20122.50 & 0.00 & 328.44 & 334541.00 & 1 \\
c52_56.txt & 20805.45 & 20903.00 & 0.00 & 3600.00 & 3606735.00 & 0 \\
c52_57.txt & 23839.38 & 23839.40 & 0.00 & 241.80 & 306059.00 & 1 \\
c52_58.txt & 23725.28 & 23934.80 & 0.01 & 3600.00 & 3575694.00 & 0 \\
c52_59.txt & 22049.98 & 22050.00 & 0.00 & 627.77 & 754831.00 & 1 \\
c52_60.txt & 22549.78 & 22549.80 & 0.00 & 423.22 & 424365.00 & 1 \\
c52_61.txt & 56409.55 & 56409.60 & 0.00 & 1838.68 & 1678779.00 & 1 \\
c52_62.txt & 45029.14 & 45254.40 & 0.00 & 3600.00 & 3364009.00 & 0 \\
c52_63.txt & 50527.95 & 50528.00 & 0.00 & 1748.00 & 1980934.00 & 1 \\
c52_64.txt & 50061.73 & 50240.20 & 0.00 & 3600.00 & 4415920.00 & 0 \\
c52_65.txt & 62262.94 & 62263.00 & 0.00 & 596.82 & 705113.00 & 1 \\
c52_66.txt & 48396.46 & 48396.50 & 0.00 & 891.94 & 780726.00 & 1 \\
c52_67.txt & 57858.94 & 57859.00 & 0.00 & 1158.98 & 1052420.00 & 1 \\
c52_68.txt & 46833.96 & 46834.00 & 0.00 & 1934.86 & 1776898.00 & 1 \\
c52_69.txt & 58657.34 & 58657.40 & 0.00 & 2391.84 & 1883456.00 & 1 \\
c52_70.txt & 47489.17 & 47579.20 & 0.00 & 3600.00 & 2668618.00 & 0 \\
c52_71.txt & 61125.14 & 61125.20 & 0.00 & 448.57 & 488910.00 & 1 \\
c52_72.txt & 48307.35 & 48307.40 & 0.00 & 1527.52 & 2027340.00 & 1 \\
c52_73.txt & 16923.60 & 16923.60 & 0.00 & 0.10 & 192.00 & 1 \\
c52_74.txt & 22493.80 & 22493.80 & 0.00 & 0.07 & 68.00 & 1 \\
c52_75.txt & 17905.80 & 17905.80 & 0.00 & 0.04 & 10.00 & 1 \\
c52_76.txt & 22717.80 & 22717.80 & 0.00 & 0.04 & 1.00 & 1 \\
c52_77.txt & 23991.00 & 23991.00 & 0.00 & 0.76 & 1067.00 & 1 \\
c52_78.txt & 34086.00 & 34086.00 & 0.00 & 1.39 & 2702.00 & 1 \\
c52_79.txt & 23348.50 & 23348.50 & 0.00 & 0.83 & 1487.00 & 1 \\
c52_80.txt & 37338.00 & 37338.00 & 0.00 & 1.00 & 2059.00 & 1 \\
c52_81.txt & 24822.60 & 24822.60 & 0.00 & 2.26 & 3157.00 & 1 \\
c52_82.txt & 41730.60 & 41730.60 & 0.00 & 10.91 & 19180.00 & 1 \\
c52_83.txt & 29855.00 & 29855.00 & 0.00 & 1.23 & 2885.00 & 1 \\
c52_84.txt & 37450.60 & 37450.60 & 0.00 & 8.34 & 15572.00 & 1 \\
c52_85.txt & 28188.40 & 28188.40 & 0.00 & 0.57 & 1641.00 & 1 \\
c52_86.txt & 33886.80 & 33886.80 & 0.00 & 0.56 & 1476.00 & 1 \\
c52_87.txt & 27593.80 & 27593.80 & 0.00 & 0.54 & 1473.00 & 1 \\
c52_88.txt & 34623.00 & 34623.00 & 0.00 & 0.16 & 368.00 & 1 \\
c52_89.txt & 33823.98 & 33824.00 & 0.00 & 5.53 & 12333.00 & 1 \\
c52_90.txt & 42633.00 & 42633.00 & 0.00 & 20.24 & 34533.00 & 1 \\
c52_91.txt & 33227.00 & 33227.00 & 0.00 & 3.08 & 8263.00 & 1 \\
c52_92.txt & 38966.00 & 38966.00 & 0.00 & 22.10 & 28134.00 & 1 \\
c52_93.txt & 39465.00 & 39465.00 & 0.00 & 8.96 & 16486.00 & 1 \\
c52_94.txt & 45048.80 & 45048.80 & 0.00 & 59.45 & 78222.00 & 1 \\
c52_95.txt & 35905.00 & 35905.00 & 0.00 & 12.35 & 22684.00 & 1 \\
c52_96.txt & 49514.40 & 49514.40 & 0.00 & 33.41 & 47824.00 & 1 \\
c52_97.txt & 66347.34 & 66347.40 & 0.00 & 101.40 & 123231.00 & 1 \\
c52_98.txt & 83029.40 & 83465.80 & 0.01 & 3600.00 & 6811192.00 & 0 \\
c52_99.txt & 74427.13 & 74427.20 & 0.00 & 1892.57 & 2212420.00 & 1 \\
c52_100.txt & 66630.94 & 66631.00 & 0.00 & 889.94 & 1015948.00 & 1 \\
c52_101.txt & 72277.21 & 73031.00 & 0.01 & 3600.00 & 4249475.00 & 0 \\
c52_102.txt & 81357.93 & 81358.00 & 0.00 & 1705.38 & 2447235.00 & 1 \\
c52_103.txt & 72008.93 & 72009.00 & 0.00 & 391.12 & 443632.00 & 1 \\
c52_104.txt & 72897.43 & 72897.50 & 0.00 & 866.63 & 1240314.00 & 1 \\
c52_105.txt & 70650.55 & 70650.60 & 0.00 & 132.33 & 168304.00 & 1 \\
c52_106.txt & 82915.84 & 83134.40 & 0.00 & 3600.00 & 3995895.00 & 0 \\
c52_107.txt & 63700.80 & 63700.80 & 0.00 & 108.50 & 137120.00 & 1 \\
c52_108.txt & 66727.60 & 66727.60 & 0.00 & 87.28 & 120460.00 & 1 \\
res_mip & 33634.31 & 33667.82 & 0.00 & 1156.45 & 1312088.98 & 89 \\
\bottomrule
\end{tabular}